import type { Listing, Owner, SavedSearch, SectionId, Thread } from "./types";

export const CITIES = [
  "all",
  "bishkek",
  "osh",
  "jalal-abad",
  "karakol",
  "cholpon-ata",
  "naryn",
  "talas",
  "batken",
  "tokmok",
  "kochkor",
] as const;

export const SECTIONS: { id: SectionId; icon: string }[] = [
  { id: "rent", icon: "home" },
  { id: "secondhand", icon: "bag" },
  { id: "cars", icon: "car" },
  { id: "car-rental", icon: "car-rent" },
  { id: "stays", icon: "hotel" },
  { id: "services", icon: "pen" },
  { id: "vacancies", icon: "briefcase" },
  { id: "construction", icon: "blocks" },
  { id: "animals", icon: "animal" },
];

export const CATEGORIES = ["furniture", "sport", "electronics"] as const;

const img = (id: string, extra = "") =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=70${extra}`;

export const OWNERS: Record<string, Owner> = {
  aida: {
    id: "aida",
    name: "Аида",
    initial: "А",
    color: "ink",
    verified: true,
    since: "2024",
    replyTime: "отвечает за 1 час",
    listingsCount: 4,
    rating: 4.9,
    online: true,
  },
  nurbek: {
    id: "nurbek",
    name: "Нурбек",
    initial: "Н",
    color: "accent-dark",
    verified: false,
    since: "2023",
    listingsCount: 7,
    rating: 4.8,
    online: false,
  },
  asel: {
    id: "asel",
    name: "Асель",
    initial: "А",
    color: "ink",
    verified: true,
    since: "2022",
    listingsCount: 3,
    rating: 4.7,
  },
};

export const LISTINGS: Listing[] = [
  {
    id: "apt-sunny",
    section: "rent",
    category: "rent",
    title: "Солнечная квартира у центра",
    titleKy: "Борборго жакын күнөстүү батир",
    titleEn: "Sunny apartment near the centre",
    price: 38000,
    previousPrice: 41000,
    unit: "month",
    city: "bishkek",
    district: "Ленинский район",
    postedAgo: "2h",
    rooms: 2,
    area: 62,
    housingKind: "apartment",
    photos: [
      img("photo-1502672260266-1c1ef2d93688"),
      img("photo-1560448204-e02f11c3d0e2"),
      img("photo-1522708323590-d24dbb6b0267"),
      img("photo-1484154218962-a197022b5858"),
    ],
    photoCredit: "Unsplash / Martin Péchy",
    description:
      "Светлая квартира с мебелью, открытой гостиной, оборудованной кухней и местом для работы из дома. Пример расположения: центр Бишкека. Месячная аренда без коммунальных платежей.",
    descriptionKy:
      "Жарык батир эмерек менен, ачык конок бөлмө, жабдылган ашкана жана үйдөн иштөө үчүн орун. Мисал жайгашуу: Бишкектин борбору. Коммуналдык төлөмдөрсүз айлык ижара.",
    descriptionEn:
      "A bright furnished apartment with an open living room, equipped kitchen and a desk for working from home. Sample location: central Bishkek. Monthly rent without utilities.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "promoted",
    utilitiesNote: "Коммунальные услуги не включены",
    safetyKind: "home",
    mapX: 12,
    mapY: 28,
    distance: "400 м от вас",
    contact: "whatsapp",
    views: 412,
    favCount: 6,
  },
  {
    id: "sofa-leather",
    section: "secondhand",
    category: "furniture",
    title: "Кожаный диван, готов к новому дому",
    titleKy: "Тери диван, жаңы үйгө даяр",
    titleEn: "Leather sofa, ready for a new home",
    price: 18500,
    city: "osh",
    postedAgo: "3d",
    condition: "good",
    photos: [
      img("photo-1555041469-a586c61ea9bc"),
      img("photo-1493663284031-b7e3aefcae8e"),
      img("photo-1540574163026-643ea20ade25"),
    ],
    photoCredit: "Unsplash / Martin Péchy",
    description:
      "Диван служил пять лет, каркас крепкий, кожа без порезов. Есть небольшая потёртость на левом подлокотнике — видно на третьем фото. Забрать нужно самостоятельно, поможем спустить.",
    descriptionKy:
      "Диван беш жыл кызмат кылган, каркас бекем, териде кесилүү жок. Сол колтукта кичине эскирүү бар. Өзүңүз алып кетесиз, түшүрүүгө жардам беребиз.",
    descriptionEn:
      "The sofa served five years. The frame is solid, the leather has no cuts. A small scuff on the left armrest shows on the third photo. Pickup only — we will help carry it down.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    specs: [
      { label: "material", value: "Натуральная кожа" },
      { label: "size", value: "210 × 90 см" },
      { label: "bargain", value: "Возможен" },
      { label: "pickup", value: "Самовывоз" },
    ],
    safetyKind: "goods",
    mapX: 48,
    mapY: 18,
    contact: "telegram",
    views: 198,
    favCount: 4,
  },
  {
    id: "bike-blue",
    section: "secondhand",
    category: "sport",
    title: "Синий велосипед для ежедневных поездок",
    titleKy: "Күнүмдүк жүрүү үчүн көк велосипед",
    titleEn: "Blue bicycle for everyday rides",
    price: 12000,
    city: "karakol",
    postedAgo: "1d",
    condition: "good",
    photos: [img("photo-1485965120184-e220f721d03e")],
    photoCredit: "Unsplash / Markus Spiske",
    description: "Городской велосипед в хорошем состоянии. Подходит для поездок по Караколу и набережной.",
    descriptionKy: "Шаардык велосипед жакшы абалда. Каракол жана жээк боюнча жүрүүгө ылайыктуу.",
    descriptionEn: "A city bike in good condition. Fine for daily rides around Karakol.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "draft",
    safetyKind: "goods",
    mapX: 68,
    mapY: 46,
    contact: "whatsapp",
    views: 64,
    favCount: 2,
  },
  {
    id: "camera-canon",
    section: "secondhand",
    category: "electronics",
    title: "Canon DSLR с объективом",
    titleKy: "Объективи бар Canon DSLR",
    titleEn: "Canon DSLR with lens",
    price: 24000,
    city: "jalal-abad",
    postedAgo: "5d",
    condition: "like-new",
    photos: [img("photo-1516035069371-29a1b244cc32")],
    photoCredit: "Unsplash / William Thomas",
    description: "Камера почти не использовалась. В комплекте объектив, ремень и сумка.",
    descriptionKy: "Камера дээрлик колдонулган эмес. Комплектте объектив, кур жана сумка бар.",
    descriptionEn: "Barely used camera. Comes with lens, strap and bag.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: false,
    status: "withdrawn",
    safetyKind: "goods",
    mapX: 28,
    mapY: 62,
    contact: "telegram",
    views: 88,
    favCount: 1,
  },
  {
    id: "apt-osh",
    section: "rent",
    category: "rent",
    title: "Квартира с мебелью в Оше",
    titleKy: "Ош шаарындагы эмеректүү батир",
    titleEn: "Furnished apartment in Osh",
    price: 25000,
    unit: "month",
    city: "osh",
    postedAgo: "6h",
    rooms: 1,
    area: 40,
    housingKind: "apartment",
    photos: [img("photo-1522708323590-d24dbb6b0267")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Уютная однокомнатная квартира с мебелью. Рядом рынок и остановки.",
    descriptionKy: "Жайлуу бир бөлмөлүү эмеректүү батир. Базар жана аялдамалар жакын.",
    descriptionEn: "A cosy one-room furnished apartment. Market and bus stops nearby.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 52,
    mapY: 18,
    contact: "whatsapp",
    views: 221,
    favCount: 5,
  },
  {
    id: "house-karakol",
    section: "rent",
    category: "rent",
    title: "Просторный дом для долгого проживания",
    titleKy: "Узак жашоо үчүн кенен үй",
    titleEn: "Spacious home for a longer stay",
    price: 32000,
    unit: "month",
    city: "karakol",
    postedAgo: "8h",
    rooms: 3,
    area: 78,
    housingKind: "house",
    photos: [img("photo-1568605114967-8130f5cd86c8")],
    photoCredit: "Unsplash / Adrian Newell",
    description: "Дом с двором у подножия гор. Подходит для семьи.",
    descriptionKy: "Тоонун этегинде короолуу үй. Үй-бүлө үчүн ылайыктуу.",
    descriptionEn: "A house with a yard at the foot of the mountains. Good for a family.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "promoted",
    safetyKind: "home",
    mapX: 70,
    mapY: 48,
    contact: "whatsapp",
    views: 310,
    favCount: 8,
  },
  {
    id: "sheep-naryn",
    section: "animals",
    category: "livestock",
    title: "Овцы с местного подворья",
    titleKy: "Жергиликтүү короодон койлор",
    titleEn: "Sheep from a local smallholding",
    price: 16000,
    city: "naryn",
    postedAgo: "12h",
    photos: [img("photo-1484557985045-edf25e1d3d4e")],
    photoCredit: "Unsplash / Jasper",
    description: "Здоровые овцы с подворья в Нарыне. Торг уместен.",
    descriptionKy: "Нарындагы короодон дени сак койлор. Соода мүмкүн.",
    descriptionEn: "Healthy sheep from a smallholding in Naryn. Bargaining welcome.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 40,
    mapY: 72,
    contact: "whatsapp",
    views: 45,
    favCount: 1,
  },
  {
    id: "camry-2018",
    section: "cars",
    category: "sedan",
    title: "Toyota Camry • 2018",
    titleKy: "Toyota Camry • 2018",
    titleEn: "Toyota Camry • 2018",
    price: 1650000,
    city: "bishkek",
    postedAgo: "1d",
    photos: [img("photo-1549317661-bd32c8ce0db2")],
    photoCredit: "Unsplash / Adrian Newell",
    description: "2018 год, 92 000 км. Один хозяин, ухоженный салон.",
    descriptionKy: "2018-жыл, 92 000 км. Бир ээси, сакталган салон.",
    descriptionEn: "2018, 92,000 km. One owner, well kept interior.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: false,
    status: "active",
    specs: [
      { label: "year", value: "2018" },
      { label: "mileage", value: "92 000 км" },
    ],
    safetyKind: "goods",
    mapX: 22,
    mapY: 36,
    contact: "telegram",
    views: 540,
    favCount: 11,
  },
  {
    id: "rav4-rental",
    section: "car-rental",
    category: "suv",
    title: "Toyota RAV4 на поездку",
    titleKy: "Сапар үчүн Toyota RAV4",
    titleEn: "Toyota RAV4 for your next trip",
    price: 4500,
    unit: "day",
    city: "bishkek",
    postedAgo: "4h",
    photos: [img("photo-1519641471654-76ce0107ad1b")],
    photoCredit: "Unsplash / William Thomas",
    description: "SUV, автомат. Выдача в Бишкеке, можно уехать на Иссык-Куль.",
    descriptionKy: "SUV, автомат. Бишкектен берүү, Ысык-Көлгө чыгууга болот.",
    descriptionEn: "SUV, automatic. Pickup in Bishkek, fine for Issyk-Kul.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    specs: [
      { label: "body", value: "SUV" },
      { label: "gear", value: "Автомат" },
    ],
    safetyKind: "goods",
    mapX: 18,
    mapY: 52,
    contact: "whatsapp",
    views: 167,
    favCount: 3,
  },
  {
    id: "guesthouse-karakol",
    section: "stays",
    category: "family",
    title: "Горный гостевой дом • семейный номер",
    titleKy: "Тоо конок үйү • үй-бүлөлүк бөлмө",
    titleEn: "Mountain guesthouse • family room",
    price: 4200,
    unit: "night",
    city: "karakol",
    postedAgo: "9h",
    photos: [img("photo-1566073771259-6a8506099945")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Семейный номер на 4 гостей. Завтрак по договорённости.",
    descriptionKy: "4 конокко үй-бүлөлүк бөлмө. Тамак макулдашуу боюнча.",
    descriptionEn: "Family room for 4 guests. Breakfast by arrangement.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 74,
    mapY: 40,
    contact: "whatsapp",
    views: 276,
    favCount: 7,
  },
  {
    id: "plumber-bishkek",
    section: "services",
    category: "repairs",
    title: "Сантехника и мелкий ремонт дома",
    titleKy: "Сантехника жана үйдү майда оңдоо",
    titleEn: "Home plumbing and small repairs",
    price: 1500,
    unit: "service",
    city: "bishkek",
    postedAgo: "3h",
    photos: [img("photo-1581578731548-c64695cc6952")],
    photoCredit: "Unsplash / Markus Spiske",
    description: "Выезд по Бишкеку в день обращения. Мелкий ремонт и сантехника.",
    descriptionKy: "Бишкек боюнча кайрылган күнү баруу. Майда оңдоо жана сантехника.",
    descriptionEn: "Same-day visits around Bishkek. Plumbing and small repairs.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 30,
    mapY: 22,
    contact: "whatsapp",
    views: 91,
    favCount: 2,
  },
  {
    id: "job-receptionist",
    section: "vacancies",
    category: "full-time",
    title: "Администратор гостевого дома",
    titleKy: "Конок үйүнүн администратору",
    titleEn: "Guesthouse receptionist",
    price: 35000,
    unit: "month",
    city: "karakol",
    postedAgo: "2d",
    photos: [img("photo-1497366216548-37526070297c")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Полный день, на месте. Русский и английский приветствуются.",
    descriptionKy: "Толук күн, жерде. Орус жана англис тили кубатталат.",
    descriptionEn: "Full-time, on-site. Russian and English are a plus.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 62,
    mapY: 58,
    contact: "telegram",
    views: 133,
    favCount: 0,
  },
  {
    id: "cement-50kg",
    section: "construction",
    category: "cement",
    title: "Цемент • мешки по 50 кг",
    titleKy: "Цемент • 50 кг баштыктар",
    titleEn: "Cement • 50 kg bags",
    price: 450,
    unit: "bag",
    city: "bishkek",
    postedAgo: "7h",
    photos: [img("photo-1517581177682-a085bb7ffb15")],
    photoCredit: "Unsplash / Markus Spiske",
    description: "Свежая партия. Самовывоз со склада в Бишкеке.",
    descriptionKy: "Жаңы партия. Бишкектеги кампадан өзүңүз алып кетүү.",
    descriptionEn: "Fresh batch. Pickup from a warehouse in Bishkek.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 8,
    mapY: 44,
    contact: "whatsapp",
    views: 77,
    favCount: 1,
  },
];

export const DEFAULT_SAVED: SavedSearch[] = [
  { id: "s1", title: "2 комнаты, Бишкек, до 40 000", newCount: 3, notify: true },
  { id: "s2", title: "Велосипеды, Каракол", newCount: 0, notify: false },
  { id: "s3", title: "Мебель, Ош, до 20 000", newCount: 1, notify: true },
];

export const DEFAULT_THREADS: Thread[] = [
  {
    id: "t-aida",
    listingId: "apt-sunny",
    ownerId: "aida",
    preview: "Салам! Квартира ещё свободна?",
    time: "09:16",
    unread: true,
    messages: [
      { id: "m1", from: "them", text: "Салам! Квартира ещё свободна?", time: "09:12" },
      {
        id: "m2",
        from: "me",
        text: "Салам! Да, свободна с 15 числа. Можете посмотреть завтра после 18:00.",
        time: "09:14",
        read: true,
      },
      { id: "m3", from: "them", text: "Отлично. Коммунальные примерно сколько выходит?", time: "09:15" },
      { id: "m4", from: "me", text: "Зимой около 3 500 сом, летом меньше.", time: "09:16", read: true },
      {
        id: "m5",
        from: "system",
        text: "Konshu не участвует в оплате. Не переводите залог до осмотра квартиры.",
        time: "",
      },
    ],
  },
  {
    id: "t-nurbek",
    listingId: "sofa-leather",
    ownerId: "nurbek",
    preview: "Диван ещё продаётся?",
    time: "вчера",
    unread: false,
    messages: [
      { id: "n1", from: "me", text: "Салам! Диван ещё продаётся?", time: "18:02", read: true },
      { id: "n2", from: "them", text: "Да, можете сегодня забрать.", time: "18:10" },
    ],
  },
];

export const MY_LISTING_IDS = ["apt-sunny", "house-karakol", "bike-blue", "guesthouse-karakol"];

export const PROMOTED_IDS = ["house-karakol", "bike-blue"];

export function listingById(id: string) {
  return LISTINGS.find((item) => item.id === id);
}

export function ownerById(id: string) {
  return OWNERS[id];
}

export function formatSom(n: number) {
  return n.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ");
}
