import type { Listing, Owner, SavedSearch, SectionId, Thread } from "./types";

export const CITIES = [
  "all",
  "bishkek",
  "osh",
  "jalal-abad",
  "karakol",
  "cholpon-ata",
  "naryn",
  "talas",
  "batken",
  "tokmok",
  "kochkor",
] as const;

export const SECTIONS: { id: SectionId; icon: string }[] = [
  { id: "rent", icon: "home" },
  { id: "secondhand", icon: "bag" },
  { id: "cars", icon: "car" },
  { id: "stays", icon: "hotel" },
  { id: "services", icon: "pen" },
  { id: "vacancies", icon: "briefcase" },
  { id: "construction", icon: "blocks" },
  { id: "animals", icon: "animal" },
];

export const CATEGORIES = [
  "furniture",
  "sport",
  "phones",
  "laptops",
  "pcs",
  "appliances",
  "kids",
  "home",
] as const;
export type GoodsCategory = (typeof CATEGORIES)[number];

export const TECH_CATEGORIES = ["phones", "laptops", "pcs", "appliances"] as const;
export type TechCategory = (typeof TECH_CATEGORIES)[number];

export function isTechCategory(category: string | null | undefined): category is TechCategory {
  return !!category && (TECH_CATEGORIES as readonly string[]).includes(category);
}

export const GOODS_KINDS: Record<GoodsCategory, readonly string[]> = {
  furniture: ["sofa", "bed", "wardrobe", "table", "kitchen-furniture"],
  sport: ["bike", "gym", "winter-sport", "tourism"],
  phones: ["smartphone", "feature-phone", "tablet", "phone-acc"],
  laptops: ["ultrabook", "gaming-laptop", "office-laptop"],
  pcs: ["desktop", "all-in-one", "monitor", "pc-parts"],
  appliances: ["fridge", "washer", "stove", "vacuum", "ac", "microwave"],
  kids: ["stroller", "kids-clothes", "toys", "car-seat", "kids-furniture"],
  home: ["dishes", "textile", "decor", "storage", "home-cleaning"],
};

export function goodsKindsOf(category: string | null | undefined): readonly string[] {
  if (!category || !(CATEGORIES as readonly string[]).includes(category)) return [];
  return GOODS_KINDS[category as GoodsCategory];
}

export const TECH_BRANDS: Record<TechCategory, readonly string[]> = {
  phones: ["apple", "samsung", "xiaomi", "huawei", "honor", "tecno"],
  laptops: ["apple", "lenovo", "hp", "asus", "acer", "dell"],
  pcs: ["apple", "lenovo", "hp", "samsung"],
  appliances: ["samsung", "lg", "bosch", "indesit", "artel", "haier"],
};

export function techBrandsOf(category: string | null | undefined): readonly string[] {
  if (!isTechCategory(category)) return [];
  return TECH_BRANDS[category];
}

export const TECH_MODELS: Record<TechCategory, Record<string, readonly string[]>> = {
  phones: {
    apple: ["iphone-13", "iphone-14", "iphone-15", "iphone-se"],
    samsung: ["galaxy-a54", "galaxy-s23", "galaxy-a15"],
    xiaomi: ["redmi-note-12", "redmi-13", "poco-x5"],
    huawei: ["huawei-p30", "nova-y70"],
    honor: ["honor-x8", "honor-x9a"],
    tecno: ["spark-10", "camon-20"],
  },
  laptops: {
    apple: ["macbook-air-m1", "macbook-pro-14"],
    lenovo: ["thinkpad-e14", "ideapad-3"],
    hp: ["pavilion-15", "elitebook-840"],
    asus: ["vivobook-15", "tuf-gaming"],
    acer: ["aspire-5", "nitro-5"],
    dell: ["inspiron-15", "latitude-5420"],
  },
  pcs: {
    apple: ["imac-24", "mac-mini-m2"],
    lenovo: ["legion-tower", "thinkcentre"],
    hp: ["pavilion-desktop", "elite-desk"],
    samsung: ["odyssey-g5", "smart-monitor-m8"],
  },
  appliances: {
    samsung: ["samsung-rb33", "samsung-ww70"],
    lg: ["lg-ga-b509", "lg-f2j"],
    bosch: ["bosch-kgn39", "bosch-wan282"],
    indesit: ["indesit-ds4180", "indesit-iwsc"],
    artel: ["artel-hd", "artel-60c"],
    haier: ["haier-c2f636", "haier-hw70"],
  },
};

export function techModelsOf(
  category: string | null | undefined,
  brand: string | null | undefined,
): readonly string[] {
  if (!isTechCategory(category) || !brand || brand === "any") return [];
  return TECH_MODELS[category][brand] ?? [];
}

export const PROPERTY_TYPES = [
  "apartment",
  "house",
  "room",
  "parking",
  "commercial",
  "land",
  "dacha",
] as const;
export type PropertyType = (typeof PROPERTY_TYPES)[number];

const LIVING_PROPERTY = new Set<string>(["any", "apartment", "house", "room", "dacha"]);
const ROOMS_PROPERTY = new Set<string>(["any", "apartment", "house", "dacha"]);
const STOCK_PROPERTY = new Set<string>(["any", "apartment", "house", "commercial", "dacha"]);

export function propertyIsLiving(type: string) {
  return LIVING_PROPERTY.has(type);
}

export function propertyShowsRooms(type: string) {
  return ROOMS_PROPERTY.has(type);
}

export function propertyShowsStock(type: string) {
  return STOCK_PROPERTY.has(type);
}

export const ANIMAL_GROUPS = ["pets", "farm"] as const;
export type AnimalGroup = (typeof ANIMAL_GROUPS)[number];

export const ANIMAL_KINDS: Record<AnimalGroup, readonly string[]> = {
  pets: ["dogs", "cats", "fish", "pet-food", "birds", "rodents", "pet-goods", "other-pets"],
  farm: ["cattle", "horses", "sheep", "goats", "chickens", "rabbits", "pigs", "other-farm"],
};

export function animalKindsOf(group: string | null | undefined): readonly string[] {
  if (group === "pets" || group === "farm") return ANIMAL_KINDS[group];
  return [];
}

export const CAR_MAKES = [
  "toyota",
  "honda",
  "hyundai",
  "kia",
  "nissan",
  "mercedes",
  "lexus",
  "lada",
] as const;
export type CarMake = (typeof CAR_MAKES)[number];

export const CAR_MODELS: Record<CarMake, readonly string[]> = {
  toyota: ["camry", "corolla", "rav4", "land-cruiser", "prado"],
  honda: ["civic", "accord", "cr-v"],
  hyundai: ["sonata", "tucson", "elantra"],
  kia: ["sportage", "rio", "k5"],
  nissan: ["x-trail", "qashqai", "patrol"],
  mercedes: ["e-class", "c-class", "gle"],
  lexus: ["rx", "lx", "es"],
  lada: ["vesta", "granta", "niva"],
};

export function carModelsOf(make: string | null | undefined): readonly string[] {
  if (!make || !(CAR_MAKES as readonly string[]).includes(make)) return [];
  return CAR_MODELS[make as CarMake];
}

export const SERVICE_CATEGORIES = [
  "repairs-finish",
  "house-build",
  "appliance-repair",
  "beauty",
  "education",
  "cleaning",
  "other",
] as const;

export const CONSTRUCTION_CATEGORIES = [
  "cement",
  "brick",
  "timber",
  "metal",
  "roofing",
  "bulk",
  "paint",
  "insulation",
] as const;

export const DEAL_KINDS = ["buy", "short", "long"] as const;

export const GIS_CITIES: Record<string, { lng: number; lat: number; zoom: number; slug: string }> = {
  bishkek: { lng: 74.5698, lat: 42.8746, zoom: 12, slug: "bishkek" },
  osh: { lng: 72.7985, lat: 40.5283, zoom: 13, slug: "osh" },
  "jalal-abad": { lng: 73.002, lat: 40.933, zoom: 13, slug: "jalalabad" },
  karakol: { lng: 78.393, lat: 42.4906, zoom: 13, slug: "karakol" },
  "cholpon-ata": { lng: 77.0806, lat: 42.6494, zoom: 13, slug: "cholpon-ata" },
  naryn: { lng: 76.001, lat: 41.428, zoom: 13, slug: "naryn" },
  talas: { lng: 72.242, lat: 42.522, zoom: 13, slug: "talas" },
  batken: { lng: 70.819, lat: 40.062, zoom: 13, slug: "batken" },
  tokmok: { lng: 75.301, lat: 42.8417, zoom: 13, slug: "tokmok" },
  kochkor: { lng: 75.689, lat: 42.216, zoom: 13, slug: "kochkor" },
};

export const DISTRICTS = [
  { id: "leninsky", city: "bishkek", name: "Ленинский район", nameKy: "Ленин району", nameEn: "Leninsky district", lng: 74.5898, lat: 42.8726 },
  { id: "oktyabr", city: "bishkek", name: "Октябрьский район", nameKy: "Октябрь району", nameEn: "Oktyabr district", lng: 74.62, lat: 42.852 },
  { id: "pervomai", city: "bishkek", name: "Первомайский район", nameKy: "Биринчи май району", nameEn: "Pervomaisky district", lng: 74.58, lat: 42.882 },
  { id: "sverdlov", city: "bishkek", name: "Свердловский район", nameKy: "Свердлов району", nameEn: "Sverdlov district", lng: 74.635, lat: 42.882 },
  { id: "djal", city: "bishkek", name: "Джал", nameKy: "Жал", nameEn: "Djal", lng: 74.546, lat: 42.837 },
  { id: "vostok5", city: "bishkek", name: "Восток-5", nameKy: "Чыгыш-5", nameEn: "Vostok-5", lng: 74.652, lat: 42.854 },
  { id: "asanbai", city: "bishkek", name: "Асанбай", nameKy: "Асанбай", nameEn: "Asanbai", lng: 74.575, lat: 42.825 },
  { id: "12mkr", city: "bishkek", name: "12 микрорайон", nameKy: "12 микрорайон", nameEn: "12th microdistrict", lng: 74.618, lat: 42.868 },
  { id: "osh-center", city: "osh", name: "Центр Оша", nameKy: "Ош борбору", nameEn: "Osh centre", lng: 72.7985, lat: 40.5283 },
  { id: "karakol-center", city: "karakol", name: "Центр Каракола", nameKy: "Каракол борбору", nameEn: "Karakol centre", lng: 78.393, lat: 42.4906 },
  { id: "tokmok-center", city: "tokmok", name: "Токмок", nameKy: "Токмок", nameEn: "Tokmok", lng: 75.301, lat: 42.8417 },
] as const;

const img = (id: string, extra = "") =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=70${extra}`;

export const OWNERS: Record<string, Owner> = {
  aida: {
    id: "aida",
    name: "Аида",
    initial: "А",
    color: "ink",
    verified: true,
    since: "2024",
    replyTime: "отвечает за 1 час",
    listingsCount: 4,
    rating: 4.9,
    online: true,
  },
  nurbek: {
    id: "nurbek",
    name: "Нурбек",
    initial: "Н",
    color: "accent-dark",
    verified: false,
    since: "2023",
    listingsCount: 7,
    rating: 4.8,
    online: false,
  },
  asel: {
    id: "asel",
    name: "Асель",
    initial: "А",
    color: "ink",
    verified: true,
    since: "2022",
    listingsCount: 3,
    rating: 4.7,
  },
};

export const LISTINGS: Listing[] = [
  {
    id: "apt-sunny",
    section: "rent",
    category: "rent",
    title: "Солнечная квартира у центра",
    titleKy: "Борборго жакын күнөстүү батир",
    titleEn: "Sunny apartment near the centre",
    price: 38000,
    previousPrice: 41000,
    unit: "month",
    city: "bishkek",
    district: "Ленинский район",
    postedAgo: "2h",
    rooms: 2,
    area: 62,
    housingKind: "apartment",
    dealKind: "long",
    lng: 74.5898,
    lat: 42.8726,
    photos: [
      img("photo-1502672260266-1c1ef2d93688"),
      img("photo-1560448204-e02f11c3d0e2"),
      img("photo-1522708323590-d24dbb6b0267"),
      img("photo-1484154218962-a197022b5858"),
    ],
    photoCredit: "Unsplash / Martin Péchy",
    description:
      "Светлая квартира с мебелью, открытой гостиной, оборудованной кухней и местом для работы из дома. Пример расположения: центр Бишкека. Месячная аренда без коммунальных платежей.",
    descriptionKy:
      "Жарык батир эмерек менен, ачык конок бөлмө, жабдылган ашкана жана үйдөн иштөө үчүн орун. Мисал жайгашуу: Бишкектин борбору. Коммуналдык төлөмдөрсүз айлык ижара.",
    descriptionEn:
      "A bright furnished apartment with an open living room, equipped kitchen and a desk for working from home. Sample location: central Bishkek. Monthly rent without utilities.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "promoted",
    utilitiesNote: "Коммунальные услуги не включены",
    safetyKind: "home",
    mapX: 12,
    mapY: 28,
    distance: "400 м от вас",
    contact: "whatsapp",
    views: 412,
    favCount: 6,
  },
  {
    id: "sofa-leather",
    section: "secondhand",
    category: "furniture",
    goodsKind: "sofa",
    title: "Кожаный диван, готов к новому дому",
    titleKy: "Тери диван, жаңы үйгө даяр",
    titleEn: "Leather sofa, ready for a new home",
    price: 18500,
    city: "osh",
    postedAgo: "3d",
    condition: "good",
    photos: [
      img("photo-1555041469-a586c61ea9bc"),
      img("photo-1493663284031-b7e3aefcae8e"),
      img("photo-1540574163026-643ea20ade25"),
    ],
    photoCredit: "Unsplash / Martin Péchy",
    description:
      "Диван служил пять лет, каркас крепкий, кожа без порезов. Есть небольшая потёртость на левом подлокотнике — видно на третьем фото. Забрать нужно самостоятельно, поможем спустить.",
    descriptionKy:
      "Диван беш жыл кызмат кылган, каркас бекем, териде кесилүү жок. Сол колтукта кичине эскирүү бар. Өзүңүз алып кетесиз, түшүрүүгө жардам беребиз.",
    descriptionEn:
      "The sofa served five years. The frame is solid, the leather has no cuts. A small scuff on the left armrest shows on the third photo. Pickup only — we will help carry it down.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    specs: [
      { label: "material", value: "Натуральная кожа" },
      { label: "size", value: "210 × 90 см" },
      { label: "bargain", value: "Возможен" },
      { label: "pickup", value: "Самовывоз" },
    ],
    safetyKind: "goods",
    mapX: 48,
    mapY: 18,
    contact: "telegram",
    views: 198,
    favCount: 4,
  },
  {
    id: "bike-blue",
    section: "secondhand",
    category: "sport",
    goodsKind: "bike",
    title: "Синий велосипед для ежедневных поездок",
    titleKy: "Күнүмдүк жүрүү үчүн көк велосипед",
    titleEn: "Blue bicycle for everyday rides",
    price: 12000,
    city: "karakol",
    postedAgo: "1d",
    condition: "good",
    photos: [img("photo-1485965120184-e220f721d03e")],
    photoCredit: "Unsplash / Markus Spiske",
    description: "Городской велосипед в хорошем состоянии. Подходит для поездок по Караколу и набережной.",
    descriptionKy: "Шаардык велосипед жакшы абалда. Каракол жана жээк боюнча жүрүүгө ылайыктуу.",
    descriptionEn: "A city bike in good condition. Fine for daily rides around Karakol.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "draft",
    safetyKind: "goods",
    mapX: 68,
    mapY: 46,
    contact: "whatsapp",
    views: 64,
    favCount: 2,
  },
  {
    id: "camera-canon",
    section: "secondhand",
    category: "phones",
    goodsKind: "phone-acc",
    title: "Canon DSLR с объективом",
    titleKy: "Объективи бар Canon DSLR",
    titleEn: "Canon DSLR with lens",
    price: 24000,
    city: "jalal-abad",
    postedAgo: "5d",
    condition: "like-new",
    photos: [img("photo-1516035069371-29a1b244cc32")],
    photoCredit: "Unsplash / William Thomas",
    description: "Камера почти не использовалась. В комплекте объектив, ремень и сумка.",
    descriptionKy: "Камера дээрлик колдонулган эмес. Комплектте объектив, кур жана сумка бар.",
    descriptionEn: "Barely used camera. Comes with lens, strap and bag.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: false,
    status: "withdrawn",
    safetyKind: "goods",
    mapX: 28,
    mapY: 62,
    contact: "telegram",
    views: 88,
    favCount: 1,
  },
  {
    id: "stroller-city",
    section: "secondhand",
    category: "kids",
    goodsKind: "stroller",
    title: "Коляска 0–3 года, почти новая",
    titleKy: "0–3 жашка коляска, дээрлик жаңы",
    titleEn: "Stroller 0–3 years, almost new",
    price: 9800,
    city: "bishkek",
    postedAgo: "2h",
    condition: "like-new",
    photos: [img("photo-1544126592-807ade215a0b")],
    photoCredit: "Unsplash",
    description:
      "Прогулочная коляска, лёгкая, складывается одной рукой. Чехол съёмный. Отдаём, потому что ребёнок вырос.",
    descriptionKy: "Жөө жүрүүчү коляска, жеңил, бир кол менен бүктөлөт. Бала чоңойгондуктан беребиз.",
    descriptionEn: "A light stroller that folds with one hand. Removable cover. Selling because the child has grown.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 34,
    mapY: 22,
    contact: "whatsapp",
    views: 76,
    favCount: 5,
  },
  {
    id: "dishes-set",
    section: "secondhand",
    category: "home",
    goodsKind: "dishes",
    title: "Набор посуды на 6 персон",
    titleKy: "6 кишилик идиш-аяк топтому",
    titleEn: "Dinnerware set for 6",
    price: 3200,
    city: "osh",
    postedAgo: "1d",
    condition: "good",
    photos: [img("photo-1600585154340-0e9986c1280b")],
    photoCredit: "Unsplash",
    description: "Тарелки, салатницы и кружки. Без сколов, после переезда не помещаются в шкаф.",
    descriptionKy: "Тарелкалар, салатницалар жана кружкалар. Жылыганда шкафка батпай калды.",
    descriptionEn: "Plates, salad bowls and mugs. No chips — they no longer fit after a move.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 52,
    mapY: 30,
    contact: "telegram",
    views: 41,
    favCount: 2,
  },
  {
    id: "dumbbells-home",
    section: "secondhand",
    category: "sport",
    goodsKind: "gym",
    title: "Гантели 2 × 8 кг",
    titleKy: "Гантелдер 2 × 8 кг",
    titleEn: "Dumbbells 2 × 8 kg",
    price: 2500,
    city: "bishkek",
    postedAgo: "5h",
    condition: "good",
    photos: [img("photo-1571902943202-507ec2618e8f")],
    photoCredit: "Unsplash",
    description: "Пара гантелей для дома. Резина целая, запаха нет. Самовывоз с Джала.",
    descriptionKy: "Үй үчүн гантелдер. Резина бүтүн. Жалдан өзүңүз алып кетиңиз.",
    descriptionEn: "A pair of home dumbbells. Rubber intact, no smell. Pickup from Djal.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 16,
    mapY: 40,
    contact: "whatsapp",
    views: 33,
    favCount: 1,
  },
  {
    id: "phone-used",
    section: "secondhand",
    category: "phones",
    goodsKind: "smartphone",
    techBrand: "samsung",
    techModel: "galaxy-a54",
    title: "Samsung Galaxy A54, 128 ГБ, без царапин",
    titleKy: "Samsung Galaxy A54, 128 ГБ, экранда сызык жок",
    titleEn: "Samsung Galaxy A54, 128 GB, unmarked screen",
    price: 18500,
    city: "bishkek",
    postedAgo: "8h",
    condition: "good",
    photos: [img("photo-1511707171634-5f897ff02aa9")],
    photoCredit: "Unsplash",
    description: "Батарея держит день. Коробка и зарядка в комплекте. Проверен на месте.",
    descriptionKy: "Батарея бир күнкө жетет. Коробка жана зарядка бар. Жерде текшеребиз.",
    descriptionEn: "Battery lasts a day. Box and charger included. Check in person before you pay.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 26,
    mapY: 44,
    contact: "telegram",
    views: 112,
    favCount: 7,
  },
  {
    id: "iphone-13",
    section: "secondhand",
    category: "phones",
    goodsKind: "smartphone",
    techBrand: "apple",
    techModel: "iphone-13",
    title: "iPhone 13, 128 ГБ, батарея 87%",
    titleKy: "iPhone 13, 128 ГБ, батарея 87%",
    titleEn: "iPhone 13, 128 GB, battery 87%",
    price: 32000,
    city: "bishkek",
    postedAgo: "3h",
    condition: "like-new",
    photos: [img("photo-1510557880182-3d4d3cba35a5")],
    photoCredit: "Unsplash",
    description: "Чехол и стекло с первого дня. Face ID работает. Встреча в центре Бишкека.",
    descriptionKy: "Чехол жана стекло биринчи күндөн. Face ID иштейт. Бишкектин борборунда жолугушабыз.",
    descriptionEn: "Case and glass from day one. Face ID works. Meet in central Bishkek.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 22,
    mapY: 36,
    contact: "whatsapp",
    views: 94,
    favCount: 8,
  },
  {
    id: "laptop-lenovo",
    section: "secondhand",
    category: "laptops",
    goodsKind: "office-laptop",
    techBrand: "lenovo",
    techModel: "ideapad-3",
    title: "Lenovo IdeaPad 3, 8/256, для учёбы",
    titleKy: "Lenovo IdeaPad 3, 8/256, окуу үчүн",
    titleEn: "Lenovo IdeaPad 3, 8/256, for study",
    price: 22000,
    city: "osh",
    postedAgo: "6h",
    condition: "good",
    photos: [img("photo-1496181133206-80ce9b88a853")],
    photoCredit: "Unsplash",
    description: "Экран 15 дюймов, зарядки хватает на день. Клавиатура кириллица. Самовывоз с центра Оша.",
    descriptionKy: "Экран 15 дюйм, зарядка бир күнгө жетет. Оштун борборунан алып кетиңиз.",
    descriptionEn: "15-inch screen, battery lasts a day. Cyrillic keyboard. Pickup in central Osh.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 48,
    mapY: 28,
    contact: "telegram",
    views: 61,
    favCount: 3,
  },
  {
    id: "pc-lenovo",
    section: "secondhand",
    category: "pcs",
    goodsKind: "desktop",
    techBrand: "lenovo",
    techModel: "legion-tower",
    title: "Lenovo Legion, игровой системный блок",
    titleKy: "Lenovo Legion, оюн системдик блогу",
    titleEn: "Lenovo Legion gaming desktop",
    price: 45000,
    city: "bishkek",
    postedAgo: "1d",
    condition: "good",
    photos: [img("photo-1587831990711-23ca6441447b")],
    photoCredit: "Unsplash",
    description: "Собрали для игр и учёбы. Монитор не входит. Можно проверить на месте.",
    descriptionKy: "Оюн жана окуу үчүн чогултулган. Монитор жок. Жерде текшерсеңиз болот.",
    descriptionEn: "Built for games and study. Monitor not included. Check it in person.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 18,
    mapY: 42,
    contact: "whatsapp",
    views: 55,
    favCount: 4,
  },
  {
    id: "fridge-artel",
    section: "secondhand",
    category: "appliances",
    goodsKind: "fridge",
    techBrand: "artel",
    techModel: "artel-hd",
    title: "Холодильник Artel, два года, без шума",
    titleKy: "Artel муздаткыч, эки жыл, ызы-чуусуз",
    titleEn: "Artel fridge, two years, quiet",
    price: 14000,
    city: "jalal-abad",
    postedAgo: "4h",
    condition: "good",
    photos: [img("photo-1571175443880-49e1d25b2bc5")],
    photoCredit: "Unsplash",
    description: "Двухкамерный, морозилка снизу. Отдаём из-за переезда. Поможем с погрузкой.",
    descriptionKy: "Эки камералуу, тоңдургуч ылдыйда. Көчкөндүктөн беребиз. Жүктөөгө жардам беребиз.",
    descriptionEn: "Two-door, freezer at the bottom. Selling because of a move. We can help load it.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 40,
    mapY: 58,
    contact: "whatsapp",
    views: 47,
    favCount: 2,
  },
  {
    id: "apt-osh",
    section: "rent",
    category: "rent",
    title: "Квартира с мебелью в Оше",
    titleKy: "Ош шаарындагы эмеректүү батир",
    titleEn: "Furnished apartment in Osh",
    price: 25000,
    unit: "month",
    city: "osh",
    postedAgo: "6h",
    rooms: 1,
    area: 40,
    housingKind: "apartment",
    dealKind: "long",
    lng: 72.7985,
    lat: 40.5283,
    photos: [img("photo-1522708323590-d24dbb6b0267")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Уютная однокомнатная квартира с мебелью. Рядом рынок и остановки.",
    descriptionKy: "Жайлуу бир бөлмөлүү эмеректүү батир. Базар жана аялдамалар жакын.",
    descriptionEn: "A cosy one-room furnished apartment. Market and bus stops nearby.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 52,
    mapY: 18,
    contact: "whatsapp",
    views: 221,
    favCount: 5,
  },
  {
    id: "house-karakol",
    section: "rent",
    category: "rent",
    title: "Просторный дом для долгого проживания",
    titleKy: "Узак жашоо үчүн кенен үй",
    titleEn: "Spacious home for a longer stay",
    price: 32000,
    unit: "month",
    city: "karakol",
    postedAgo: "8h",
    rooms: 3,
    area: 78,
    housingKind: "house",
    dealKind: "long",
    lng: 78.393,
    lat: 42.4906,
    photos: [img("photo-1568605114967-8130f5cd86c8")],
    photoCredit: "Unsplash / Adrian Newell",
    description: "Дом с двором у подножия гор. Подходит для семьи.",
    descriptionKy: "Тоонун этегинде короолуу үй. Үй-бүлө үчүн ылайыктуу.",
    descriptionEn: "A house with a yard at the foot of the mountains. Good for a family.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "promoted",
    safetyKind: "home",
    mapX: 70,
    mapY: 48,
    contact: "whatsapp",
    views: 310,
    favCount: 8,
  },
  {
    id: "short-apt-djal",
    section: "rent",
    category: "rent",
    title: "Квартира посуточно на Джале",
    titleKy: "Жалда суткалык батир",
    titleEn: "Daily apartment in Djal",
    price: 2800,
    unit: "day",
    city: "bishkek",
    district: "Джал",
    postedAgo: "4h",
    rooms: 1,
    area: 38,
    housingKind: "apartment",
    dealKind: "short",
    lng: 74.546,
    lat: 42.837,
    photos: [img("photo-1502672023488-70e23437e25b")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Чистая однушка, Wi-Fi, всё для короткой поездки. Заселение с 14:00.",
    descriptionKy: "Таза бир бөлмө, Wi-Fi. Кирүү саат 14:00дөн.",
    descriptionEn: "A clean studio with Wi-Fi for a short stay. Check-in from 14:00.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 24,
    mapY: 42,
    contact: "telegram",
    views: 154,
    favCount: 4,
  },
  {
    id: "buy-apt-vostok",
    section: "rent",
    category: "rent",
    title: "2-комнатная на продажу, Восток-5",
    titleKy: "Чыгыш-5те сатылуучу 2 бөлмө",
    titleEn: "2-room apartment for sale, Vostok-5",
    price: 6800000,
    city: "bishkek",
    district: "Восток-5",
    postedAgo: "1d",
    rooms: 2,
    area: 58,
    housingKind: "apartment",
    dealKind: "buy",
    stockKind: "resale",
    lng: 74.652,
    lat: 42.854,
    photos: [img("photo-1560448204-603b3fc33ddc")],
    photoCredit: "Unsplash / Ralph Kayden",
    description: "Кирпичный дом, 5 этаж из 9. Документы готовы. Торг уместен.",
    descriptionKy: "Кирпич үй, 9 кабаттын 5-и. Документтер даяр.",
    descriptionEn: "Brick building, 5th of 9 floors. Papers ready. Bargaining welcome.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 36,
    mapY: 22,
    contact: "whatsapp",
    views: 89,
    favCount: 3,
  },
  {
    id: "buy-house-tokmok",
    section: "rent",
    category: "rent",
    title: "Дом в Токмоке, участок 6 соток",
    titleKy: "Токмоктогу үй, 6 соток",
    titleEn: "House in Tokmok, 6 sotok plot",
    price: 4200000,
    city: "tokmok",
    district: "Токмок",
    postedAgo: "2d",
    rooms: 4,
    area: 96,
    housingKind: "house",
    dealKind: "buy",
    stockKind: "resale",
    lng: 75.301,
    lat: 42.8417,
    photos: [img("photo-1570129477492-45c003edd2be")],
    photoCredit: "Unsplash / Todd Kent",
    description: "Дом во дворе, сад и гараж. До Бишкека — около 40 минут.",
    descriptionKy: "Короодогу үй, бакча жана гараж. Бишкекке ~40 мүнөт.",
    descriptionEn: "A yard house with a garden and garage. About 40 minutes to Bishkek.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 44,
    mapY: 56,
    contact: "whatsapp",
    views: 61,
    favCount: 2,
  },
  {
    id: "buy-apt-newbuild",
    section: "rent",
    category: "rent",
    title: "Новостройка у 12 мкр, сдача в этом году",
    titleKy: "12 микрорайондогу жаңы үй, быйыл тапшырылат",
    titleEn: "New build near the 12th microdistrict, handover this year",
    price: 9200000,
    city: "bishkek",
    district: "12 микрорайон",
    postedAgo: "5h",
    rooms: 2,
    area: 64,
    housingKind: "apartment",
    dealKind: "buy",
    stockKind: "newbuild",
    lng: 74.618,
    lat: 42.868,
    photos: [img("photo-1545324418-cc1a3fa10c00")],
    photoCredit: "Unsplash / Lance Anderson",
    description: "Монолит, 8 этаж из 12. От застройщика, без отделки. Рассрочка на 24 месяца.",
    descriptionKy: "Монолит, 12 кабаттын 8-и. Куруучудан, жасалгасыз. 24 айга бөлүп төлөө.",
    descriptionEn: "Monolith, 8th of 12 floors. From the developer, unfinished. 24-month instalments.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 28,
    mapY: 24,
    contact: "telegram",
    views: 142,
    favCount: 6,
  },
  {
    id: "room-center",
    section: "rent",
    category: "rent",
    title: "Комната в квартире у Филармонии",
    titleKy: "Филармония жанындагы батирдеги бөлмө",
    titleEn: "Room in a flat near the Philharmonic",
    price: 8000,
    unit: "month",
    city: "bishkek",
    district: "Первомайский район",
    postedAgo: "3h",
    rooms: 1,
    area: 14,
    housingKind: "room",
    dealKind: "long",
    lng: 74.58,
    lat: 42.882,
    photos: [img("photo-1522771739844-6a9f6d5f14af")],
    photoCredit: "Unsplash",
    description: "Отдельная комната, общая кухня и ванная. Соседи спокойные, интернет есть.",
    descriptionKy: "Өзүнчө бөлмө, жалпы ашкана жана ванна. Коңшулар тынч, интернет бар.",
    descriptionEn: "A private room with a shared kitchen and bathroom. Quiet flatmates, wifi included.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 20,
    mapY: 30,
    contact: "whatsapp",
    views: 58,
    favCount: 3,
  },
  {
    id: "parking-oktyabr",
    section: "rent",
    category: "rent",
    title: "Машиноместо в подземном паркинге",
    titleKy: "Жер төлөдөгү унаа орду",
    titleEn: "Underground parking space",
    price: 3500,
    unit: "month",
    city: "bishkek",
    district: "Октябрьский район",
    postedAgo: "6h",
    housingKind: "parking",
    dealKind: "long",
    lng: 74.62,
    lat: 42.852,
    photos: [img("photo-1506521781263-d8422e82f27a")],
    photoCredit: "Unsplash",
    description: "Закрытый паркинг, шлагбаум, охрана. Высота подходит для кроссовера.",
    descriptionKy: "Жабык паркинг, шлагбаум, күзөт. Кроссоверге ылайыктуу.",
    descriptionEn: "Gated underground parking with a barrier and a guard. Height fits a crossover.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 36,
    mapY: 38,
    contact: "telegram",
    views: 22,
    favCount: 1,
  },
  {
    id: "shop-center",
    section: "rent",
    category: "rent",
    title: "Торговое помещение в центре, 48 м²",
    titleKy: "Борбордогу соода жайы, 48 м²",
    titleEn: "Retail space downtown, 48 m²",
    price: 55000,
    unit: "month",
    city: "bishkek",
    district: "Ленинский район",
    postedAgo: "1d",
    area: 48,
    housingKind: "commercial",
    dealKind: "long",
    lng: 74.5698,
    lat: 42.8746,
    photos: [img("photo-1497366216548-37526070297c")],
    photoCredit: "Unsplash",
    description: "Первая линия, витрины на улицу. Подойдёт под магазин или офис.",
    descriptionKy: "Биринчи линия, көчөгө витрина. Дүкөн же кеңсе үчүн ылайыктуу.",
    descriptionEn: "Street-facing windows on the first line. Fine for a shop or a small office.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: false,
    status: "active",
    safetyKind: "home",
    mapX: 14,
    mapY: 26,
    contact: "whatsapp",
    views: 67,
    favCount: 2,
  },
  {
    id: "land-kochkor",
    section: "rent",
    category: "rent",
    title: "Участок 8 соток, Кочкор",
    titleKy: "8 соток жер, Кочкор",
    titleEn: "8 sotok plot in Kochkor",
    price: 850000,
    city: "kochkor",
    postedAgo: "2d",
    housingKind: "land",
    dealKind: "buy",
    lng: 75.689,
    lat: 42.216,
    photos: [img("photo-1500382017468-9049fed747ef")],
    photoCredit: "Unsplash",
    description: "Ровный участок под дом или огород. Документы в порядке, свет по границе.",
    descriptionKy: "Үй же огород үчүн түз жер. Документтер даяр, чекте жарык бар.",
    descriptionEn: "A level plot for a house or a garden. Papers in order, power at the boundary.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    specs: [{ label: "size", value: "8 соток" }],
    safetyKind: "goods",
    mapX: 60,
    mapY: 50,
    contact: "telegram",
    views: 31,
    favCount: 2,
  },
  {
    id: "dacha-issyk",
    section: "rent",
    category: "rent",
    title: "Дача у Иссык-Куля, сад и баня",
    titleKy: "Ысык-Көлдөгү дача, бакча жана мончо",
    titleEn: "Issyk-Kul dacha with a garden and banya",
    price: 2100000,
    city: "cholpon-ata",
    postedAgo: "4h",
    rooms: 3,
    area: 54,
    housingKind: "dacha",
    dealKind: "buy",
    stockKind: "resale",
    lng: 77.0806,
    lat: 42.6494,
    photos: [img("photo-1568605114967-8130f3a36994")],
    photoCredit: "Unsplash",
    description: "Дом на участке, плодовые деревья, баня. До озера 12 минут на машине.",
    descriptionKy: "Участтогу үй, жемиш бактары, мончо. Көлгө машина менен 12 мүнөт.",
    descriptionEn: "House on a plot, fruit trees and a banya. Twelve minutes by car to the lake.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 72,
    mapY: 22,
    contact: "whatsapp",
    views: 88,
    favCount: 4,
  },
  {
    id: "sheep-naryn",
    section: "animals",
    category: "livestock",
    animalGroup: "farm",
    animalKind: "sheep",
    title: "Овцы с местного подворья",
    titleKy: "Жергиликтүү короодон койлор",
    titleEn: "Sheep from a local smallholding",
    price: 16000,
    city: "naryn",
    postedAgo: "12h",
    photos: [img("photo-1484557985045-edf25e1d3d4e")],
    photoCredit: "Unsplash / Jasper",
    description: "Здоровые овцы с подворья в Нарыне. Торг уместен.",
    descriptionKy: "Нарындагы короодон дени сак койлор. Соода мүмкүн.",
    descriptionEn: "Healthy sheep from a smallholding in Naryn. Bargaining welcome.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 40,
    mapY: 72,
    contact: "whatsapp",
    views: 45,
    favCount: 1,
  },
  {
    id: "puppy-bishkek",
    section: "animals",
    animalGroup: "pets",
    animalKind: "dogs",
    title: "Щенки лабрадора, 2 месяца",
    titleKy: "2 айлык лабрадор күчүктөрү",
    titleEn: "Labrador puppies, 2 months",
    price: 15000,
    city: "bishkek",
    postedAgo: "3h",
    photos: [img("photo-1587300003388-59208cc962cb")],
    photoCredit: "Unsplash",
    description: "Мальчик и девочка, к лотку приучены, первая прививка сделана. Отдам с запасом корма.",
    descriptionKy: "Эркек жана ургаачы, лотокко үйрөтүлгөн, биринчи эмдөө жасалган.",
    descriptionEn: "A boy and a girl, litter trained, first vaccine done. A starter bag of food included.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 24,
    mapY: 32,
    contact: "whatsapp",
    views: 96,
    favCount: 8,
  },
  {
    id: "cat-osh",
    section: "animals",
    animalGroup: "pets",
    animalKind: "cats",
    title: "Британская кошка, стерилизована",
    titleKy: "Британ мышыгы, стерилизацияланган",
    titleEn: "British shorthair cat, spayed",
    price: 6000,
    city: "osh",
    postedAgo: "1d",
    photos: [img("photo-1514888286974-6c03e2ca1dba")],
    photoCredit: "Unsplash",
    description: "Спокойная, к лотку приучена. Отдаём в добрые руки: переезд, с собой не берём.",
    descriptionKy: "Тынч, лотокко үйрөтүлгөн. Жакшы колго беребиз.",
    descriptionEn: "Calm and litter trained. Rehoming because of a move.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 50,
    mapY: 40,
    contact: "telegram",
    views: 54,
    favCount: 6,
  },
  {
    id: "pet-food-bag",
    section: "animals",
    animalGroup: "pets",
    animalKind: "pet-food",
    title: "Корм для собак, мешок 15 кг",
    titleKy: "Иттерге тоют, 15 кг баштык",
    titleEn: "Dog food, 15 kg bag",
    price: 2800,
    unit: "bag",
    city: "bishkek",
    postedAgo: "5h",
    photos: [img("photo-1589924691995-400dc9e23826")],
    photoCredit: "Unsplash",
    description: "Сухой корм, срок годный. Открыли один мешок — этот целый, не подошёл по составу.",
    descriptionKy: "Кургак тоют, мөөнөтү жарактуу. Бир баштык ачылган, бул бүтүн.",
    descriptionEn: "Dry food, in date. We opened one bag — this one is sealed, the formula did not suit us.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 18,
    mapY: 44,
    contact: "whatsapp",
    views: 19,
    favCount: 1,
  },
  {
    id: "cattle-talas",
    section: "animals",
    animalGroup: "farm",
    animalKind: "cattle",
    title: "Корова, дойная, Талас",
    titleKy: "Саан уй, Талас",
    titleEn: "Dairy cow, Talas",
    price: 85000,
    city: "talas",
    postedAgo: "8h",
    photos: [img("photo-1527153857715-9692a9ec330e")],
    photoCredit: "Unsplash",
    description: "Дойная корова, телёнок рядом. Документы и осмотр на месте.",
    descriptionKy: "Саан уй, музоо жанында. Документтер жана кароо жерде.",
    descriptionEn: "A dairy cow with a calf nearby. Papers and inspection on site.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 62,
    mapY: 48,
    contact: "telegram",
    views: 38,
    favCount: 2,
  },
  {
    id: "chickens-kochkor",
    section: "animals",
    animalGroup: "farm",
    animalKind: "chickens",
    title: "Куры-несушки, 20 голов",
    titleKy: "Жумурткалаган тооктор, 20 баш",
    titleEn: "Laying hens, 20 birds",
    price: 450,
    city: "kochkor",
    postedAgo: "2h",
    photos: [img("photo-1548550023-2bdb3c5beed7")],
    photoCredit: "Unsplash",
    description: "Несушки, цена за голову. Можно забрать всех сразу — торг.",
    descriptionKy: "Жумурткалаган тооктор, баасы бир башка. Баарын алууга болот.",
    descriptionEn: "Layers, price per bird. Take all twenty and we can talk the price down.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 70,
    mapY: 56,
    contact: "whatsapp",
    views: 27,
    favCount: 1,
  },
  {
    id: "camry-2018",
    section: "cars",
    category: "sedan",
    title: "Toyota Camry • 2018",
    titleKy: "Toyota Camry • 2018",
    titleEn: "Toyota Camry • 2018",
    price: 1650000,
    city: "bishkek",
    postedAgo: "1d",
    photos: [img("photo-1549317661-bd32c8ce0db2")],
    photoCredit: "Unsplash / Adrian Newell",
    description: "2018 год, 92 000 км. Один хозяин, ухоженный салон.",
    descriptionKy: "2018-жыл, 92 000 км. Бир ээси, сакталган салон.",
    descriptionEn: "2018, 92,000 km. One owner, well kept interior.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: false,
    status: "active",
    bodyKind: "sedan",
    carMake: "toyota",
    carModel: "camry",
    year: 2018,
    specs: [
      { label: "year", value: "2018" },
      { label: "mileage", value: "92 000 км" },
    ],
    safetyKind: "goods",
    mapX: 22,
    mapY: 36,
    contact: "telegram",
    views: 540,
    favCount: 11,
  },
  {
    id: "rav4-rental",
    section: "car-rental",
    category: "suv",
    title: "Toyota RAV4 на поездку",
    titleKy: "Сапар үчүн Toyota RAV4",
    titleEn: "Toyota RAV4 for your next trip",
    price: 4500,
    unit: "day",
    city: "bishkek",
    postedAgo: "4h",
    photos: [img("photo-1519641471654-76ce0107ad1b")],
    photoCredit: "Unsplash / William Thomas",
    description: "SUV, автомат. Выдача в Бишкеке, можно уехать на Иссык-Куль.",
    descriptionKy: "SUV, автомат. Бишкектен берүү, Ысык-Көлгө чыгууга болот.",
    descriptionEn: "SUV, automatic. Pickup in Bishkek, fine for Issyk-Kul.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    bodyKind: "suv",
    gearKind: "auto",
    carMake: "toyota",
    carModel: "rav4",
    specs: [
      { label: "body", value: "SUV" },
      { label: "gear", value: "Автомат" },
    ],
    safetyKind: "goods",
    mapX: 18,
    mapY: 52,
    contact: "whatsapp",
    views: 167,
    favCount: 3,
  },
  {
    id: "honda-crv",
    section: "cars",
    category: "suv",
    title: "Honda CR-V • 2019",
    titleKy: "Honda CR-V • 2019",
    titleEn: "Honda CR-V • 2019",
    price: 1980000,
    city: "bishkek",
    postedAgo: "6h",
    photos: [img("photo-1609521263047-f8a39724dbaa")],
    photoCredit: "Unsplash",
    description: "Один хозяин, полный комплект. Зимняя резина в комплекте.",
    descriptionKy: "Бир ээси, толук комплект. Кышкы резинка бар.",
    descriptionEn: "One owner, full kit. Winter tyres included.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    bodyKind: "suv",
    carMake: "honda",
    carModel: "cr-v",
    year: 2019,
    safetyKind: "goods",
    mapX: 30,
    mapY: 34,
    contact: "whatsapp",
    views: 210,
    favCount: 5,
  },
  {
    id: "tucson-osh",
    section: "cars",
    category: "suv",
    title: "Hyundai Tucson • 2020",
    titleKy: "Hyundai Tucson • 2020",
    titleEn: "Hyundai Tucson • 2020",
    price: 2150000,
    city: "osh",
    postedAgo: "2d",
    photos: [img("photo-1552519507-da3b142c6e3d")],
    photoCredit: "Unsplash",
    description: "Официальный ввоз, сервисная книжка. Пробег 48 000 км.",
    descriptionKy: "Расмий алып келүү, сервис китепчеси. Жүрүүсү 48 000 км.",
    descriptionEn: "Official import, service book. 48,000 km.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: false,
    status: "active",
    bodyKind: "suv",
    carMake: "hyundai",
    carModel: "tucson",
    year: 2020,
    safetyKind: "goods",
    mapX: 44,
    mapY: 42,
    contact: "telegram",
    views: 188,
    favCount: 4,
  },
  {
    id: "granta-tokmok",
    section: "cars",
    category: "sedan",
    title: "Lada Granta • 2021",
    titleKy: "Lada Granta • 2021",
    titleEn: "Lada Granta • 2021",
    price: 620000,
    city: "tokmok",
    postedAgo: "4h",
    photos: [img("photo-1494976388531-d1058494cdd8")],
    photoCredit: "Unsplash",
    description: "Простая в обслуживании, расход небольшой. Идеально по городу.",
    descriptionKy: "Тейлөөсү оңой, чыгымы аз. Шаар үчүн ылайыктуу.",
    descriptionEn: "Easy to service, light on fuel. Fine for town.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    bodyKind: "sedan",
    carMake: "lada",
    carModel: "granta",
    year: 2021,
    safetyKind: "goods",
    mapX: 38,
    mapY: 50,
    contact: "whatsapp",
    views: 74,
    favCount: 2,
  },
  {
    id: "sportage-rent",
    section: "car-rental",
    category: "suv",
    title: "Kia Sportage на неделю",
    titleKy: "Kia Sportage бир жумага",
    titleEn: "Kia Sportage for a week",
    price: 3800,
    unit: "day",
    city: "bishkek",
    postedAgo: "1d",
    photos: [img("photo-1605559424843-9e4c228bf1c2")],
    photoCredit: "Unsplash",
    description: "Автомат, полный бак при выдаче. Можно на Иссык-Куль.",
    descriptionKy: "Автомат, толук бак. Ысык-Көлгө чыгууга болот.",
    descriptionEn: "Automatic, full tank at pickup. Fine for Issyk-Kul.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    bodyKind: "suv",
    gearKind: "auto",
    carMake: "kia",
    carModel: "sportage",
    safetyKind: "goods",
    mapX: 26,
    mapY: 46,
    contact: "whatsapp",
    views: 91,
    favCount: 3,
  },
  {
    id: "guesthouse-karakol",
    section: "stays",
    category: "family",
    title: "Горный гостевой дом • семейный номер",
    titleKy: "Тоо конок үйү • үй-бүлөлүк бөлмө",
    titleEn: "Mountain guesthouse • family room",
    price: 4200,
    unit: "night",
    city: "karakol",
    postedAgo: "9h",
    photos: [img("photo-1566073771259-6a8506099945")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Семейный номер на 4 гостей. Завтрак по договорённости.",
    descriptionKy: "4 конокко үй-бүлөлүк бөлмө. Тамак макулдашуу боюнча.",
    descriptionEn: "Family room for 4 guests. Breakfast by arrangement.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 74,
    mapY: 40,
    contact: "whatsapp",
    views: 276,
    favCount: 7,
  },
  {
    id: "hotel-cholpon",
    section: "stays",
    category: "family",
    title: "Номер у берега Иссык-Куля",
    titleKy: "Ысык-Көл жээгиндеги бөлмө",
    titleEn: "Room on the Issyk-Kul shore",
    price: 6500,
    unit: "night",
    city: "cholpon-ata",
    postedAgo: "4h",
    photos: [img("photo-1582719478250-c89cae4dc85b")],
    photoCredit: "Unsplash / visuella",
    description: "Двухместный номер, 3 минуты до пляжа. Завтрак включён. Можно с детьми.",
    descriptionKy: "Эки кишилик бөлмө, пляжга 3 мүнөт. Эртең мененки тамак кирет.",
    descriptionEn: "Double room, 3 minutes to the beach. Breakfast included. Children welcome.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 62,
    mapY: 28,
    contact: "telegram",
    views: 188,
    favCount: 9,
  },
  {
    id: "plumber-bishkek",
    section: "services",
    category: "repairs-finish",
    title: "Сантехника и мелкий ремонт дома",
    titleKy: "Сантехника жана үйдү майда оңдоо",
    titleEn: "Home plumbing and small repairs",
    price: 1500,
    unit: "service",
    city: "bishkek",
    postedAgo: "3h",
    photos: [img("photo-1581578731548-c64695cc6952")],
    photoCredit: "Unsplash / Markus Spiske",
    description: "Выезд по Бишкеку в день обращения. Мелкий ремонт и сантехника.",
    descriptionKy: "Бишкек боюнча кайрылган күнү баруу. Майда оңдоо жана сантехника.",
    descriptionEn: "Same-day visits around Bishkek. Plumbing and small repairs.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 30,
    mapY: 22,
    contact: "whatsapp",
    views: 91,
    favCount: 2,
  },
  {
    id: "build-house-bishkek",
    section: "services",
    category: "house-build",
    title: "Строительство домов под ключ",
    titleKy: "Үйлөрдү ачкычка чейин куруу",
    titleEn: "Turnkey house construction",
    price: 28000,
    unit: "service",
    city: "bishkek",
    postedAgo: "1d",
    photos: [img("photo-1503387762-592deb58ef4e")],
    photoCredit: "Unsplash / Markus Spiske",
    description: "Фундамент, стены, крыша и отделка. Смета после выезда на участок. Работаем по Бишкеку и Чуйской области.",
    descriptionKy: "Фундамент, дубал, чатыр жана жасалгалоо. Смета участка чыккандан кийин. Бишкек жана Чүй облусу.",
    descriptionEn: "Foundation, walls, roof and finishing. Quote after a site visit. Bishkek and Chui region.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 26,
    mapY: 30,
    contact: "whatsapp",
    views: 154,
    favCount: 3,
  },
  {
    id: "appliance-osh",
    section: "services",
    category: "appliance-repair",
    title: "Ремонт стиральных машин и холодильников",
    titleKy: "Кир жуугуч жана муздаткыч оңдоо",
    titleEn: "Washing machine and fridge repair",
    price: 800,
    unit: "service",
    city: "osh",
    postedAgo: "6h",
    photos: [img("photo-1556911220-e15b29be8c8f")],
    photoCredit: "Unsplash / William Thomas",
    description: "Выезд на дом в Оше. Диагностика на месте, запчасти под заказ. Гарантия на работу 3 месяца.",
    descriptionKy: "Ошто үйгө баруу. Диагностика жеринде, тетиктер заказ менен. Ишке 3 ай кепилдик.",
    descriptionEn: "Home visits in Osh. On-site diagnosis, parts to order. Three-month work warranty.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 50,
    mapY: 20,
    contact: "telegram",
    views: 72,
    favCount: 1,
  },
  {
    id: "beauty-bishkek",
    section: "services",
    category: "beauty",
    title: "Маникюр, брови и укладки",
    titleKy: "Маникюр, каш жана чач жасалгалоо",
    titleEn: "Manicure, brows and styling",
    price: 1200,
    unit: "service",
    city: "bishkek",
    postedAgo: "4h",
    photos: [img("photo-1560066984-138dadb4c035")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Студия в центре Бишкека. Запись в Instagram или по телефону. Стерильные инструменты.",
    descriptionKy: "Бишкектин борборундагы студия. Instagram же телефон аркылуу жазылуу. Стерилдүү аспаптар.",
    descriptionEn: "Studio in central Bishkek. Book via Instagram or phone. Sterile tools.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 16,
    mapY: 26,
    contact: "whatsapp",
    views: 210,
    favCount: 8,
  },
  {
    id: "tutor-karakol",
    section: "services",
    category: "education",
    title: "Репетитор по математике и английскому",
    titleKy: "Математика жана англис тили боюнча репетитор",
    titleEn: "Maths and English tutor",
    price: 700,
    unit: "service",
    city: "karakol",
    postedAgo: "8h",
    photos: [img("photo-1503676260728-1c00da094a0b")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Занятия для школьников 5–11 класс. Очно в Караколе или онлайн. Пробный урок — 30 минут.",
    descriptionKy: "5–11-класстар үчүн. Караколдо же онлайн. Сыноо сабагы — 30 мүнөт.",
    descriptionEn: "Lessons for years 5–11. In person in Karakol or online. A 30-minute trial lesson.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 68,
    mapY: 50,
    contact: "telegram",
    views: 98,
    favCount: 4,
  },
  {
    id: "cleaning-bishkek",
    section: "services",
    category: "cleaning",
    title: "Уборка квартир после ремонта и поддерживающая",
    titleKy: "Оңдоодон кийинки жана үзгүлтүксүз тазалоо",
    titleEn: "Post-renovation and regular apartment cleaning",
    price: 2500,
    unit: "service",
    city: "bishkek",
    postedAgo: "5h",
    photos: [img("photo-1581578017093-cd30f2c34ec4")],
    photoCredit: "Unsplash / Markus Spiske",
    description: "Бригада из двух человек, свои средства и пылесос. Окно, пол, кухня, санузел. Выезд в день заявки.",
    descriptionKy: "Эки кишилик бригада, өз каражаттары жана чаң соргуч. Терезе, пол, ашкана, даараткана.",
    descriptionEn: "A two-person crew with supplies and a vacuum. Windows, floors, kitchen, bathroom. Same-day visits.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 20,
    mapY: 38,
    contact: "whatsapp",
    views: 119,
    favCount: 5,
  },
  {
    id: "service-photo-osh",
    section: "services",
    category: "other",
    title: "Фотосъёмка мероприятий в Оше",
    titleKy: "Ошто иш-чараларды сүрөткө тартуу",
    titleEn: "Event photography in Osh",
    price: 4500,
    unit: "service",
    city: "osh",
    postedAgo: "6h",
    photos: [img("photo-1516035069371-29a1b244cc32")],
    photoCredit: "Unsplash / Benjamin Sow",
    description:
      "Свадьбы, дни рождения, корпоративы. Отдаю готовые фото в тот же день. Своя студия не нужна — выезжаю к вам.",
    descriptionKy:
      "Тойлор, туулган күндөр. Сүрөттөрдү ошол эле күнү берем. Студия керек эмес — өзүңөргө барам.",
    descriptionEn:
      "Weddings, birthdays, corporate events. Photos the same day. I come to you — no studio needed.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 71,
    mapY: 63,
    contact: "whatsapp",
    views: 64,
    favCount: 3,
  },
  {
    id: "job-receptionist",
    section: "vacancies",
    category: "full-time",
    title: "Администратор гостевого дома",
    titleKy: "Конок үйүнүн администратору",
    titleEn: "Guesthouse receptionist",
    price: 35000,
    unit: "month",
    city: "karakol",
    postedAgo: "2d",
    photos: [img("photo-1497366216548-37526070297c")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Полный день, на месте. Русский и английский приветствуются.",
    descriptionKy: "Толук күн, жерде. Орус жана англис тили кубатталат.",
    descriptionEn: "Full-time, on-site. Russian and English are a plus.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 62,
    mapY: 58,
    contact: "telegram",
    views: 133,
    favCount: 0,
  },
  {
    id: "cement-50kg",
    section: "construction",
    category: "cement",
    title: "Цемент • мешки по 50 кг",
    titleKy: "Цемент • 50 кг баштыктар",
    titleEn: "Cement • 50 kg bags",
    price: 450,
    unit: "bag",
    city: "bishkek",
    postedAgo: "7h",
    photos: [img("photo-1517581177682-a085bb7ffb15")],
    photoCredit: "Unsplash / Markus Spiske",
    description: "Свежая партия. Самовывоз со склада в Бишкеке.",
    descriptionKy: "Жаңы партия. Бишкектеги кампадан өзүңүз алып кетүү.",
    descriptionEn: "Fresh batch. Pickup from a warehouse in Bishkek.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 8,
    mapY: 44,
    contact: "whatsapp",
    views: 77,
    favCount: 1,
  },
  {
    id: "brick-red",
    section: "construction",
    category: "brick",
    title: "Кирпич рядовой, поддон",
    titleKy: "Катар кирпич, поддон",
    titleEn: "Common brick, pallet",
    price: 12,
    city: "bishkek",
    postedAgo: "5h",
    photos: [img("photo-1599619585752-c3edb42b0716")],
    photoCredit: "Unsplash",
    description: "Красный кирпич с завода. Самовывоз с Аламедина. Торг от пяти поддонов.",
    descriptionKy: "Кызыл кирпич заводдон. Аламединден өзүңүз алып кетиңиз. Беш поддондон соодалашабыз.",
    descriptionEn: "Red factory brick. Pickup from Alamedin. Bargain from five pallets.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 14,
    mapY: 48,
    contact: "whatsapp",
    views: 41,
    favCount: 2,
  },
  {
    id: "timber-board",
    section: "construction",
    category: "timber",
    title: "Доска обрезная 25 мм, хвоя",
    titleKy: "Кесилген такта 25 мм, ийне жалбырактуу",
    titleEn: "Edged board 25 mm, pine",
    price: 280,
    city: "karakol",
    postedAgo: "1d",
    photos: [img("photo-1416879595882-3373a0480b5b")],
    photoCredit: "Unsplash",
    description: "Сухая доска на стропила и обрешётку. Меряем на складе в Караколе.",
    descriptionKy: "Кургак такта стропила жана обрешёткага. Караколдогу кампада өлчөйбүз.",
    descriptionEn: "Dry board for rafters and batten. Measure it at the Karakol yard.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 70,
    mapY: 52,
    contact: "telegram",
    views: 36,
    favCount: 1,
  },
  {
    id: "roofing-sheet",
    section: "construction",
    category: "roofing",
    title: "Профнастил на кровлю, цвет шоколад",
    titleKy: "Чатырга профнастил, шоколад түс",
    titleEn: "Roofing profile sheet, chocolate colour",
    price: 890,
    city: "osh",
    postedAgo: "3h",
    photos: [img("photo-1503387762-592deb58ef4e")],
    photoCredit: "Unsplash",
    description: "Лист 0,45 мм. Режем в размер. Можно заказать конёк и саморезы.",
    descriptionKy: "Лист 0,45 мм. Өлчөмгө кесебиз. Конёк жана саморез заказ кылсаңыз болот.",
    descriptionEn: "0.45 mm sheet. Cut to size. Ridge and screws can be ordered.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 50,
    mapY: 34,
    contact: "whatsapp",
    views: 58,
    favCount: 4,
  },
  {
    id: "keramzit-bulk",
    section: "construction",
    category: "bulk",
    title: "Керамзит, мешки и россыпь",
    titleKy: "Керамзит, баштык жана үймөк",
    titleEn: "Expanded clay, bags and bulk",
    price: 180,
    unit: "bag",
    city: "bishkek",
    postedAgo: "6h",
    photos: [img("photo-1589939705384-5185137a7f0f")],
    photoCredit: "Unsplash",
    description: "Фракция 10–20. На стяжку и утепление. Доставим по Бишкеку от десяти мешков.",
    descriptionKy: "Фракция 10–20. Стяжка жана жылуулоо үчүн. Он баштыктан Бишкекке жеткиребиз.",
    descriptionEn: "10–20 fraction. For screed and insulation. Delivery in Bishkek from ten bags.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 20,
    mapY: 38,
    contact: "whatsapp",
    views: 29,
    favCount: 2,
  },
];

export const DEFAULT_SAVED: SavedSearch[] = [
  { id: "s1", title: "2 комнаты, Бишкек, до 40 000", newCount: 3, notify: true },
  { id: "s2", title: "Велосипеды, Каракол", newCount: 0, notify: false },
  { id: "s3", title: "Мебель, Ош, до 20 000", newCount: 1, notify: true },
];

export const DEFAULT_THREADS: Thread[] = [
  {
    id: "t-aida",
    listingId: "apt-sunny",
    ownerId: "aida",
    preview: "Салам! Квартира ещё свободна?",
    time: "09:16",
    unread: true,
    messages: [
      { id: "m1", from: "them", text: "Салам! Квартира ещё свободна?", time: "09:12" },
      {
        id: "m2",
        from: "me",
        text: "Салам! Да, свободна с 15 числа. Можете посмотреть завтра после 18:00.",
        time: "09:14",
        read: true,
      },
      { id: "m3", from: "them", text: "Отлично. Коммунальные примерно сколько выходит?", time: "09:15" },
      { id: "m4", from: "me", text: "Зимой около 3 500 сом, летом меньше.", time: "09:16", read: true },
      {
        id: "m5",
        from: "system",
        text: "Konshu не участвует в оплате. Не переводите залог до осмотра квартиры.",
        time: "",
      },
    ],
  },
  {
    id: "t-nurbek",
    listingId: "sofa-leather",
    ownerId: "nurbek",
    preview: "Диван ещё продаётся?",
    time: "вчера",
    unread: false,
    messages: [
      { id: "n1", from: "me", text: "Салам! Диван ещё продаётся?", time: "18:02", read: true },
      { id: "n2", from: "them", text: "Да, можете сегодня забрать.", time: "18:10" },
    ],
  },
];

export const MY_LISTING_IDS = ["apt-sunny", "house-karakol", "bike-blue", "guesthouse-karakol"];

export const PROMOTED_IDS = ["house-karakol", "bike-blue"];

export function listingById(id: string) {
  return LISTINGS.find((item) => item.id === id);
}

export function ownerById(id: string) {
  return OWNERS[id];
}

export function formatSom(n: number) {
  return n.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ");
}
