import type { Listing, Owner, SavedSearch, SectionId, Thread } from "./types";

export const CITIES = [
  "all",
  "bishkek",
  "osh",
  "jalal-abad",
  "karakol",
  "cholpon-ata",
  "naryn",
  "talas",
  "batken",
  "tokmok",
  "kochkor",
] as const;

export const SECTIONS: { id: SectionId; icon: string }[] = [
  { id: "rent", icon: "home" },
  { id: "secondhand", icon: "bag" },
  { id: "cars", icon: "car" },
  { id: "stays", icon: "hotel" },
  { id: "services", icon: "pen" },
  { id: "vacancies", icon: "briefcase" },
  { id: "construction", icon: "blocks" },
  { id: "animals", icon: "animal" },
];

export const CATEGORIES = ["furniture", "sport", "electronics"] as const;

export const SERVICE_CATEGORIES = [
  "repairs-finish",
  "house-build",
  "appliance-repair",
  "beauty",
  "education",
  "cleaning",
  "other",
] as const;

export const DEAL_KINDS = ["buy", "short", "long"] as const;

export const GIS_CITIES: Record<string, { lng: number; lat: number; zoom: number; slug: string }> = {
  bishkek: { lng: 74.5698, lat: 42.8746, zoom: 12, slug: "bishkek" },
  osh: { lng: 72.7985, lat: 40.5283, zoom: 13, slug: "osh" },
  "jalal-abad": { lng: 73.002, lat: 40.933, zoom: 13, slug: "jalalabad" },
  karakol: { lng: 78.393, lat: 42.4906, zoom: 13, slug: "karakol" },
  "cholpon-ata": { lng: 77.0806, lat: 42.6494, zoom: 13, slug: "cholpon-ata" },
  naryn: { lng: 76.001, lat: 41.428, zoom: 13, slug: "naryn" },
  talas: { lng: 72.242, lat: 42.522, zoom: 13, slug: "talas" },
  batken: { lng: 70.819, lat: 40.062, zoom: 13, slug: "batken" },
  tokmok: { lng: 75.301, lat: 42.8417, zoom: 13, slug: "tokmok" },
  kochkor: { lng: 75.689, lat: 42.216, zoom: 13, slug: "kochkor" },
};

export const DISTRICTS = [
  { id: "leninsky", city: "bishkek", name: "Ленинский район", nameKy: "Ленин району", nameEn: "Leninsky district", lng: 74.5898, lat: 42.8726 },
  { id: "oktyabr", city: "bishkek", name: "Октябрьский район", nameKy: "Октябрь району", nameEn: "Oktyabr district", lng: 74.62, lat: 42.852 },
  { id: "pervomai", city: "bishkek", name: "Первомайский район", nameKy: "Биринчи май району", nameEn: "Pervomaisky district", lng: 74.58, lat: 42.882 },
  { id: "sverdlov", city: "bishkek", name: "Свердловский район", nameKy: "Свердлов району", nameEn: "Sverdlov district", lng: 74.635, lat: 42.882 },
  { id: "djal", city: "bishkek", name: "Джал", nameKy: "Жал", nameEn: "Djal", lng: 74.546, lat: 42.837 },
  { id: "vostok5", city: "bishkek", name: "Восток-5", nameKy: "Чыгыш-5", nameEn: "Vostok-5", lng: 74.652, lat: 42.854 },
  { id: "asanbai", city: "bishkek", name: "Асанбай", nameKy: "Асанбай", nameEn: "Asanbai", lng: 74.575, lat: 42.825 },
  { id: "12mkr", city: "bishkek", name: "12 микрорайон", nameKy: "12 микрорайон", nameEn: "12th microdistrict", lng: 74.618, lat: 42.868 },
  { id: "osh-center", city: "osh", name: "Центр Оша", nameKy: "Ош борбору", nameEn: "Osh centre", lng: 72.7985, lat: 40.5283 },
  { id: "karakol-center", city: "karakol", name: "Центр Каракола", nameKy: "Каракол борбору", nameEn: "Karakol centre", lng: 78.393, lat: 42.4906 },
  { id: "tokmok-center", city: "tokmok", name: "Токмок", nameKy: "Токмок", nameEn: "Tokmok", lng: 75.301, lat: 42.8417 },
] as const;

const img = (id: string, extra = "") =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=70${extra}`;

export const OWNERS: Record<string, Owner> = {
  aida: {
    id: "aida",
    name: "Аида",
    initial: "А",
    color: "ink",
    verified: true,
    since: "2024",
    replyTime: "отвечает за 1 час",
    listingsCount: 4,
    rating: 4.9,
    online: true,
  },
  nurbek: {
    id: "nurbek",
    name: "Нурбек",
    initial: "Н",
    color: "accent-dark",
    verified: false,
    since: "2023",
    listingsCount: 7,
    rating: 4.8,
    online: false,
  },
  asel: {
    id: "asel",
    name: "Асель",
    initial: "А",
    color: "ink",
    verified: true,
    since: "2022",
    listingsCount: 3,
    rating: 4.7,
  },
};

export const LISTINGS: Listing[] = [
  {
    id: "apt-sunny",
    section: "rent",
    category: "rent",
    title: "Солнечная квартира у центра",
    titleKy: "Борборго жакын күнөстүү батир",
    titleEn: "Sunny apartment near the centre",
    price: 38000,
    previousPrice: 41000,
    unit: "month",
    city: "bishkek",
    district: "Ленинский район",
    postedAgo: "2h",
    rooms: 2,
    area: 62,
    housingKind: "apartment",
    dealKind: "long",
    lng: 74.5898,
    lat: 42.8726,
    photos: [
      img("photo-1502672260266-1c1ef2d93688"),
      img("photo-1560448204-e02f11c3d0e2"),
      img("photo-1522708323590-d24dbb6b0267"),
      img("photo-1484154218962-a197022b5858"),
    ],
    photoCredit: "Unsplash / Martin Péchy",
    description:
      "Светлая квартира с мебелью, открытой гостиной, оборудованной кухней и местом для работы из дома. Пример расположения: центр Бишкека. Месячная аренда без коммунальных платежей.",
    descriptionKy:
      "Жарык батир эмерек менен, ачык конок бөлмө, жабдылган ашкана жана үйдөн иштөө үчүн орун. Мисал жайгашуу: Бишкектин борбору. Коммуналдык төлөмдөрсүз айлык ижара.",
    descriptionEn:
      "A bright furnished apartment with an open living room, equipped kitchen and a desk for working from home. Sample location: central Bishkek. Monthly rent without utilities.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "promoted",
    utilitiesNote: "Коммунальные услуги не включены",
    safetyKind: "home",
    mapX: 12,
    mapY: 28,
    distance: "400 м от вас",
    contact: "whatsapp",
    views: 412,
    favCount: 6,
  },
  {
    id: "sofa-leather",
    section: "secondhand",
    category: "furniture",
    title: "Кожаный диван, готов к новому дому",
    titleKy: "Тери диван, жаңы үйгө даяр",
    titleEn: "Leather sofa, ready for a new home",
    price: 18500,
    city: "osh",
    postedAgo: "3d",
    condition: "good",
    photos: [
      img("photo-1555041469-a586c61ea9bc"),
      img("photo-1493663284031-b7e3aefcae8e"),
      img("photo-1540574163026-643ea20ade25"),
    ],
    photoCredit: "Unsplash / Martin Péchy",
    description:
      "Диван служил пять лет, каркас крепкий, кожа без порезов. Есть небольшая потёртость на левом подлокотнике — видно на третьем фото. Забрать нужно самостоятельно, поможем спустить.",
    descriptionKy:
      "Диван беш жыл кызмат кылган, каркас бекем, териде кесилүү жок. Сол колтукта кичине эскирүү бар. Өзүңүз алып кетесиз, түшүрүүгө жардам беребиз.",
    descriptionEn:
      "The sofa served five years. The frame is solid, the leather has no cuts. A small scuff on the left armrest shows on the third photo. Pickup only — we will help carry it down.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    specs: [
      { label: "material", value: "Натуральная кожа" },
      { label: "size", value: "210 × 90 см" },
      { label: "bargain", value: "Возможен" },
      { label: "pickup", value: "Самовывоз" },
    ],
    safetyKind: "goods",
    mapX: 48,
    mapY: 18,
    contact: "telegram",
    views: 198,
    favCount: 4,
  },
  {
    id: "bike-blue",
    section: "secondhand",
    category: "sport",
    title: "Синий велосипед для ежедневных поездок",
    titleKy: "Күнүмдүк жүрүү үчүн көк велосипед",
    titleEn: "Blue bicycle for everyday rides",
    price: 12000,
    city: "karakol",
    postedAgo: "1d",
    condition: "good",
    photos: [img("photo-1485965120184-e220f721d03e")],
    photoCredit: "Unsplash / Markus Spiske",
    description: "Городской велосипед в хорошем состоянии. Подходит для поездок по Караколу и набережной.",
    descriptionKy: "Шаардык велосипед жакшы абалда. Каракол жана жээк боюнча жүрүүгө ылайыктуу.",
    descriptionEn: "A city bike in good condition. Fine for daily rides around Karakol.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "draft",
    safetyKind: "goods",
    mapX: 68,
    mapY: 46,
    contact: "whatsapp",
    views: 64,
    favCount: 2,
  },
  {
    id: "camera-canon",
    section: "secondhand",
    category: "electronics",
    title: "Canon DSLR с объективом",
    titleKy: "Объективи бар Canon DSLR",
    titleEn: "Canon DSLR with lens",
    price: 24000,
    city: "jalal-abad",
    postedAgo: "5d",
    condition: "like-new",
    photos: [img("photo-1516035069371-29a1b244cc32")],
    photoCredit: "Unsplash / William Thomas",
    description: "Камера почти не использовалась. В комплекте объектив, ремень и сумка.",
    descriptionKy: "Камера дээрлик колдонулган эмес. Комплектте объектив, кур жана сумка бар.",
    descriptionEn: "Barely used camera. Comes with lens, strap and bag.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: false,
    status: "withdrawn",
    safetyKind: "goods",
    mapX: 28,
    mapY: 62,
    contact: "telegram",
    views: 88,
    favCount: 1,
  },
  {
    id: "apt-osh",
    section: "rent",
    category: "rent",
    title: "Квартира с мебелью в Оше",
    titleKy: "Ош шаарындагы эмеректүү батир",
    titleEn: "Furnished apartment in Osh",
    price: 25000,
    unit: "month",
    city: "osh",
    postedAgo: "6h",
    rooms: 1,
    area: 40,
    housingKind: "apartment",
    dealKind: "long",
    lng: 72.7985,
    lat: 40.5283,
    photos: [img("photo-1522708323590-d24dbb6b0267")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Уютная однокомнатная квартира с мебелью. Рядом рынок и остановки.",
    descriptionKy: "Жайлуу бир бөлмөлүү эмеректүү батир. Базар жана аялдамалар жакын.",
    descriptionEn: "A cosy one-room furnished apartment. Market and bus stops nearby.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 52,
    mapY: 18,
    contact: "whatsapp",
    views: 221,
    favCount: 5,
  },
  {
    id: "house-karakol",
    section: "rent",
    category: "rent",
    title: "Просторный дом для долгого проживания",
    titleKy: "Узак жашоо үчүн кенен үй",
    titleEn: "Spacious home for a longer stay",
    price: 32000,
    unit: "month",
    city: "karakol",
    postedAgo: "8h",
    rooms: 3,
    area: 78,
    housingKind: "house",
    dealKind: "long",
    lng: 78.393,
    lat: 42.4906,
    photos: [img("photo-1568605114967-8130f5cd86c8")],
    photoCredit: "Unsplash / Adrian Newell",
    description: "Дом с двором у подножия гор. Подходит для семьи.",
    descriptionKy: "Тоонун этегинде короолуу үй. Үй-бүлө үчүн ылайыктуу.",
    descriptionEn: "A house with a yard at the foot of the mountains. Good for a family.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "promoted",
    safetyKind: "home",
    mapX: 70,
    mapY: 48,
    contact: "whatsapp",
    views: 310,
    favCount: 8,
  },
  {
    id: "short-apt-djal",
    section: "rent",
    category: "rent",
    title: "Квартира посуточно на Джале",
    titleKy: "Жалда суткалык батир",
    titleEn: "Daily apartment in Djal",
    price: 2800,
    unit: "day",
    city: "bishkek",
    district: "Джал",
    postedAgo: "4h",
    rooms: 1,
    area: 38,
    housingKind: "apartment",
    dealKind: "short",
    lng: 74.546,
    lat: 42.837,
    photos: [img("photo-1502672023488-70e23437e25b")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Чистая однушка, Wi-Fi, всё для короткой поездки. Заселение с 14:00.",
    descriptionKy: "Таза бир бөлмө, Wi-Fi. Кирүү саат 14:00дөн.",
    descriptionEn: "A clean studio with Wi-Fi for a short stay. Check-in from 14:00.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 24,
    mapY: 42,
    contact: "telegram",
    views: 154,
    favCount: 4,
  },
  {
    id: "buy-apt-vostok",
    section: "rent",
    category: "rent",
    title: "2-комнатная на продажу, Восток-5",
    titleKy: "Чыгыш-5те сатылуучу 2 бөлмө",
    titleEn: "2-room apartment for sale, Vostok-5",
    price: 6800000,
    city: "bishkek",
    district: "Восток-5",
    postedAgo: "1d",
    rooms: 2,
    area: 58,
    housingKind: "apartment",
    dealKind: "buy",
    stockKind: "resale",
    lng: 74.652,
    lat: 42.854,
    photos: [img("photo-1560448204-603b3fc33ddc")],
    photoCredit: "Unsplash / Ralph Kayden",
    description: "Кирпичный дом, 5 этаж из 9. Документы готовы. Торг уместен.",
    descriptionKy: "Кирпич үй, 9 кабаттын 5-и. Документтер даяр.",
    descriptionEn: "Brick building, 5th of 9 floors. Papers ready. Bargaining welcome.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 36,
    mapY: 22,
    contact: "whatsapp",
    views: 89,
    favCount: 3,
  },
  {
    id: "buy-house-tokmok",
    section: "rent",
    category: "rent",
    title: "Дом в Токмоке, участок 6 соток",
    titleKy: "Токмоктогу үй, 6 соток",
    titleEn: "House in Tokmok, 6 sotok plot",
    price: 4200000,
    city: "tokmok",
    district: "Токмок",
    postedAgo: "2d",
    rooms: 4,
    area: 96,
    housingKind: "house",
    dealKind: "buy",
    stockKind: "resale",
    lng: 75.301,
    lat: 42.8417,
    photos: [img("photo-1570129477492-45c003edd2be")],
    photoCredit: "Unsplash / Todd Kent",
    description: "Дом во дворе, сад и гараж. До Бишкека — около 40 минут.",
    descriptionKy: "Короодогу үй, бакча жана гараж. Бишкекке ~40 мүнөт.",
    descriptionEn: "A yard house with a garden and garage. About 40 minutes to Bishkek.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 44,
    mapY: 56,
    contact: "whatsapp",
    views: 61,
    favCount: 2,
  },
  {
    id: "buy-apt-newbuild",
    section: "rent",
    category: "rent",
    title: "Новостройка у 12 мкр, сдача в этом году",
    titleKy: "12 микрорайондогу жаңы үй, быйыл тапшырылат",
    titleEn: "New build near the 12th microdistrict, handover this year",
    price: 9200000,
    city: "bishkek",
    district: "12 микрорайон",
    postedAgo: "5h",
    rooms: 2,
    area: 64,
    housingKind: "apartment",
    dealKind: "buy",
    stockKind: "newbuild",
    lng: 74.618,
    lat: 42.868,
    photos: [img("photo-1545324418-cc1a3fa10c00")],
    photoCredit: "Unsplash / Lance Anderson",
    description: "Монолит, 8 этаж из 12. От застройщика, без отделки. Рассрочка на 24 месяца.",
    descriptionKy: "Монолит, 12 кабаттын 8-и. Куруучудан, жасалгасыз. 24 айга бөлүп төлөө.",
    descriptionEn: "Monolith, 8th of 12 floors. From the developer, unfinished. 24-month instalments.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 28,
    mapY: 24,
    contact: "telegram",
    views: 142,
    favCount: 6,
  },
  {
    id: "sheep-naryn",
    section: "animals",
    category: "livestock",
    title: "Овцы с местного подворья",
    titleKy: "Жергиликтүү короодон койлор",
    titleEn: "Sheep from a local smallholding",
    price: 16000,
    city: "naryn",
    postedAgo: "12h",
    photos: [img("photo-1484557985045-edf25e1d3d4e")],
    photoCredit: "Unsplash / Jasper",
    description: "Здоровые овцы с подворья в Нарыне. Торг уместен.",
    descriptionKy: "Нарындагы короодон дени сак койлор. Соода мүмкүн.",
    descriptionEn: "Healthy sheep from a smallholding in Naryn. Bargaining welcome.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 40,
    mapY: 72,
    contact: "whatsapp",
    views: 45,
    favCount: 1,
  },
  {
    id: "camry-2018",
    section: "cars",
    category: "sedan",
    title: "Toyota Camry • 2018",
    titleKy: "Toyota Camry • 2018",
    titleEn: "Toyota Camry • 2018",
    price: 1650000,
    city: "bishkek",
    postedAgo: "1d",
    photos: [img("photo-1549317661-bd32c8ce0db2")],
    photoCredit: "Unsplash / Adrian Newell",
    description: "2018 год, 92 000 км. Один хозяин, ухоженный салон.",
    descriptionKy: "2018-жыл, 92 000 км. Бир ээси, сакталган салон.",
    descriptionEn: "2018, 92,000 km. One owner, well kept interior.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: false,
    status: "active",
    bodyKind: "sedan",
    year: 2018,
    specs: [
      { label: "year", value: "2018" },
      { label: "mileage", value: "92 000 км" },
    ],
    safetyKind: "goods",
    mapX: 22,
    mapY: 36,
    contact: "telegram",
    views: 540,
    favCount: 11,
  },
  {
    id: "rav4-rental",
    section: "car-rental",
    category: "suv",
    title: "Toyota RAV4 на поездку",
    titleKy: "Сапар үчүн Toyota RAV4",
    titleEn: "Toyota RAV4 for your next trip",
    price: 4500,
    unit: "day",
    city: "bishkek",
    postedAgo: "4h",
    photos: [img("photo-1519641471654-76ce0107ad1b")],
    photoCredit: "Unsplash / William Thomas",
    description: "SUV, автомат. Выдача в Бишкеке, можно уехать на Иссык-Куль.",
    descriptionKy: "SUV, автомат. Бишкектен берүү, Ысык-Көлгө чыгууга болот.",
    descriptionEn: "SUV, automatic. Pickup in Bishkek, fine for Issyk-Kul.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    bodyKind: "suv",
    gearKind: "auto",
    specs: [
      { label: "body", value: "SUV" },
      { label: "gear", value: "Автомат" },
    ],
    safetyKind: "goods",
    mapX: 18,
    mapY: 52,
    contact: "whatsapp",
    views: 167,
    favCount: 3,
  },
  {
    id: "guesthouse-karakol",
    section: "stays",
    category: "family",
    title: "Горный гостевой дом • семейный номер",
    titleKy: "Тоо конок үйү • үй-бүлөлүк бөлмө",
    titleEn: "Mountain guesthouse • family room",
    price: 4200,
    unit: "night",
    city: "karakol",
    postedAgo: "9h",
    photos: [img("photo-1566073771259-6a8506099945")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Семейный номер на 4 гостей. Завтрак по договорённости.",
    descriptionKy: "4 конокко үй-бүлөлүк бөлмө. Тамак макулдашуу боюнча.",
    descriptionEn: "Family room for 4 guests. Breakfast by arrangement.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 74,
    mapY: 40,
    contact: "whatsapp",
    views: 276,
    favCount: 7,
  },
  {
    id: "hotel-cholpon",
    section: "stays",
    category: "family",
    title: "Номер у берега Иссык-Куля",
    titleKy: "Ысык-Көл жээгиндеги бөлмө",
    titleEn: "Room on the Issyk-Kul shore",
    price: 6500,
    unit: "night",
    city: "cholpon-ata",
    postedAgo: "4h",
    photos: [img("photo-1582719478250-c89cae4dc85b")],
    photoCredit: "Unsplash / visuella",
    description: "Двухместный номер, 3 минуты до пляжа. Завтрак включён. Можно с детьми.",
    descriptionKy: "Эки кишилик бөлмө, пляжга 3 мүнөт. Эртең мененки тамак кирет.",
    descriptionEn: "Double room, 3 minutes to the beach. Breakfast included. Children welcome.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "home",
    mapX: 62,
    mapY: 28,
    contact: "telegram",
    views: 188,
    favCount: 9,
  },
  {
    id: "plumber-bishkek",
    section: "services",
    category: "repairs-finish",
    title: "Сантехника и мелкий ремонт дома",
    titleKy: "Сантехника жана үйдү майда оңдоо",
    titleEn: "Home plumbing and small repairs",
    price: 1500,
    unit: "service",
    city: "bishkek",
    postedAgo: "3h",
    photos: [img("photo-1581578731548-c64695cc6952")],
    photoCredit: "Unsplash / Markus Spiske",
    description: "Выезд по Бишкеку в день обращения. Мелкий ремонт и сантехника.",
    descriptionKy: "Бишкек боюнча кайрылган күнү баруу. Майда оңдоо жана сантехника.",
    descriptionEn: "Same-day visits around Bishkek. Plumbing and small repairs.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 30,
    mapY: 22,
    contact: "whatsapp",
    views: 91,
    favCount: 2,
  },
  {
    id: "build-house-bishkek",
    section: "services",
    category: "house-build",
    title: "Строительство домов под ключ",
    titleKy: "Үйлөрдү ачкычка чейин куруу",
    titleEn: "Turnkey house construction",
    price: 28000,
    unit: "service",
    city: "bishkek",
    postedAgo: "1d",
    photos: [img("photo-1503387762-592deb58ef4e")],
    photoCredit: "Unsplash / Markus Spiske",
    description: "Фундамент, стены, крыша и отделка. Смета после выезда на участок. Работаем по Бишкеку и Чуйской области.",
    descriptionKy: "Фундамент, дубал, чатыр жана жасалгалоо. Смета участка чыккандан кийин. Бишкек жана Чүй облусу.",
    descriptionEn: "Foundation, walls, roof and finishing. Quote after a site visit. Bishkek and Chui region.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 26,
    mapY: 30,
    contact: "whatsapp",
    views: 154,
    favCount: 3,
  },
  {
    id: "appliance-osh",
    section: "services",
    category: "appliance-repair",
    title: "Ремонт стиральных машин и холодильников",
    titleKy: "Кир жуугуч жана муздаткыч оңдоо",
    titleEn: "Washing machine and fridge repair",
    price: 800,
    unit: "service",
    city: "osh",
    postedAgo: "6h",
    photos: [img("photo-1556911220-e15b29be8c8f")],
    photoCredit: "Unsplash / William Thomas",
    description: "Выезд на дом в Оше. Диагностика на месте, запчасти под заказ. Гарантия на работу 3 месяца.",
    descriptionKy: "Ошто үйгө баруу. Диагностика жеринде, тетиктер заказ менен. Ишке 3 ай кепилдик.",
    descriptionEn: "Home visits in Osh. On-site diagnosis, parts to order. Three-month work warranty.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 50,
    mapY: 20,
    contact: "telegram",
    views: 72,
    favCount: 1,
  },
  {
    id: "beauty-bishkek",
    section: "services",
    category: "beauty",
    title: "Маникюр, брови и укладки",
    titleKy: "Маникюр, каш жана чач жасалгалоо",
    titleEn: "Manicure, brows and styling",
    price: 1200,
    unit: "service",
    city: "bishkek",
    postedAgo: "4h",
    photos: [img("photo-1560066984-138dadb4c035")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Студия в центре Бишкека. Запись в Instagram или по телефону. Стерильные инструменты.",
    descriptionKy: "Бишкектин борборундагы студия. Instagram же телефон аркылуу жазылуу. Стерилдүү аспаптар.",
    descriptionEn: "Studio in central Bishkek. Book via Instagram or phone. Sterile tools.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 16,
    mapY: 26,
    contact: "whatsapp",
    views: 210,
    favCount: 8,
  },
  {
    id: "tutor-karakol",
    section: "services",
    category: "education",
    title: "Репетитор по математике и английскому",
    titleKy: "Математика жана англис тили боюнча репетитор",
    titleEn: "Maths and English tutor",
    price: 700,
    unit: "service",
    city: "karakol",
    postedAgo: "8h",
    photos: [img("photo-1503676260728-1c00da094a0b")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Занятия для школьников 5–11 класс. Очно в Караколе или онлайн. Пробный урок — 30 минут.",
    descriptionKy: "5–11-класстар үчүн. Караколдо же онлайн. Сыноо сабагы — 30 мүнөт.",
    descriptionEn: "Lessons for years 5–11. In person in Karakol or online. A 30-minute trial lesson.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 68,
    mapY: 50,
    contact: "telegram",
    views: 98,
    favCount: 4,
  },
  {
    id: "cleaning-bishkek",
    section: "services",
    category: "cleaning",
    title: "Уборка квартир после ремонта и поддерживающая",
    titleKy: "Оңдоодон кийинки жана үзгүлтүксүз тазалоо",
    titleEn: "Post-renovation and regular apartment cleaning",
    price: 2500,
    unit: "service",
    city: "bishkek",
    postedAgo: "5h",
    photos: [img("photo-1581578017093-cd30f2c34ec4")],
    photoCredit: "Unsplash / Markus Spiske",
    description: "Бригада из двух человек, свои средства и пылесос. Окно, пол, кухня, санузел. Выезд в день заявки.",
    descriptionKy: "Эки кишилик бригада, өз каражаттары жана чаң соргуч. Терезе, пол, ашкана, даараткана.",
    descriptionEn: "A two-person crew with supplies and a vacuum. Windows, floors, kitchen, bathroom. Same-day visits.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 20,
    mapY: 38,
    contact: "whatsapp",
    views: 119,
    favCount: 5,
  },
  {
    id: "service-photo-osh",
    section: "services",
    category: "other",
    title: "Фотосъёмка мероприятий в Оше",
    titleKy: "Ошто иш-чараларды сүрөткө тартуу",
    titleEn: "Event photography in Osh",
    price: 4500,
    unit: "service",
    city: "osh",
    postedAgo: "6h",
    photos: [img("photo-1516035069371-29a1b244cc32")],
    photoCredit: "Unsplash / Benjamin Sow",
    description:
      "Свадьбы, дни рождения, корпоративы. Отдаю готовые фото в тот же день. Своя студия не нужна — выезжаю к вам.",
    descriptionKy:
      "Тойлор, туулган күндөр. Сүрөттөрдү ошол эле күнү берем. Студия керек эмес — өзүңөргө барам.",
    descriptionEn:
      "Weddings, birthdays, corporate events. Photos the same day. I come to you — no studio needed.",
    ownerId: "aida",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 71,
    mapY: 63,
    contact: "whatsapp",
    views: 64,
    favCount: 3,
  },
  {
    id: "job-receptionist",
    section: "vacancies",
    category: "full-time",
    title: "Администратор гостевого дома",
    titleKy: "Конок үйүнүн администратору",
    titleEn: "Guesthouse receptionist",
    price: 35000,
    unit: "month",
    city: "karakol",
    postedAgo: "2d",
    photos: [img("photo-1497366216548-37526070297c")],
    photoCredit: "Unsplash / Anna Hunko",
    description: "Полный день, на месте. Русский и английский приветствуются.",
    descriptionKy: "Толук күн, жерде. Орус жана англис тили кубатталат.",
    descriptionEn: "Full-time, on-site. Russian and English are a plus.",
    ownerId: "asel",
    verified: true,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 62,
    mapY: 58,
    contact: "telegram",
    views: 133,
    favCount: 0,
  },
  {
    id: "cement-50kg",
    section: "construction",
    category: "cement",
    title: "Цемент • мешки по 50 кг",
    titleKy: "Цемент • 50 кг баштыктар",
    titleEn: "Cement • 50 kg bags",
    price: 450,
    unit: "bag",
    city: "bishkek",
    postedAgo: "7h",
    photos: [img("photo-1517581177682-a085bb7ffb15")],
    photoCredit: "Unsplash / Markus Spiske",
    description: "Свежая партия. Самовывоз со склада в Бишкеке.",
    descriptionKy: "Жаңы партия. Бишкектеги кампадан өзүңүз алып кетүү.",
    descriptionEn: "Fresh batch. Pickup from a warehouse in Bishkek.",
    ownerId: "nurbek",
    verified: false,
    hasPhoto: true,
    noAgent: true,
    status: "active",
    safetyKind: "goods",
    mapX: 8,
    mapY: 44,
    contact: "whatsapp",
    views: 77,
    favCount: 1,
  },
];

export const DEFAULT_SAVED: SavedSearch[] = [
  { id: "s1", title: "2 комнаты, Бишкек, до 40 000", newCount: 3, notify: true },
  { id: "s2", title: "Велосипеды, Каракол", newCount: 0, notify: false },
  { id: "s3", title: "Мебель, Ош, до 20 000", newCount: 1, notify: true },
];

export const DEFAULT_THREADS: Thread[] = [
  {
    id: "t-aida",
    listingId: "apt-sunny",
    ownerId: "aida",
    preview: "Салам! Квартира ещё свободна?",
    time: "09:16",
    unread: true,
    messages: [
      { id: "m1", from: "them", text: "Салам! Квартира ещё свободна?", time: "09:12" },
      {
        id: "m2",
        from: "me",
        text: "Салам! Да, свободна с 15 числа. Можете посмотреть завтра после 18:00.",
        time: "09:14",
        read: true,
      },
      { id: "m3", from: "them", text: "Отлично. Коммунальные примерно сколько выходит?", time: "09:15" },
      { id: "m4", from: "me", text: "Зимой около 3 500 сом, летом меньше.", time: "09:16", read: true },
      {
        id: "m5",
        from: "system",
        text: "Konshu не участвует в оплате. Не переводите залог до осмотра квартиры.",
        time: "",
      },
    ],
  },
  {
    id: "t-nurbek",
    listingId: "sofa-leather",
    ownerId: "nurbek",
    preview: "Диван ещё продаётся?",
    time: "вчера",
    unread: false,
    messages: [
      { id: "n1", from: "me", text: "Салам! Диван ещё продаётся?", time: "18:02", read: true },
      { id: "n2", from: "them", text: "Да, можете сегодня забрать.", time: "18:10" },
    ],
  },
];

export const MY_LISTING_IDS = ["apt-sunny", "house-karakol", "bike-blue", "guesthouse-karakol"];

export const PROMOTED_IDS = ["house-karakol", "bike-blue"];

export function listingById(id: string) {
  return LISTINGS.find((item) => item.id === id);
}

export function ownerById(id: string) {
  return OWNERS[id];
}

export function formatSom(n: number) {
  return n.toString().replace(/\B(?=(\d{3})+(?!\d))/g, " ");
}
