import type { Shop, ShopProduct } from "./types";

const now = "2026-04-12T10:00:00.000Z";

function product(partial: Omit<ShopProduct, "currency" | "updatedAt" | "createdAt" | "published"> & Partial<Pick<ShopProduct, "published">>): ShopProduct {
  return {
    currency: "KGS",
    updatedAt: now,
    createdAt: now,
    published: true,
    ...partial,
  };
}

export const SEED_SHOPS: Shop[] = [
  {
    id: "seed-dordoi-fruit",
    name: "Ряд «Апа Айгуль»",
    ownerPhone: "555000101",
    ownerName: "Айгуль",
    category: "food",
    extraCategories: [],
    kinds: ["food-produce", "food-sweets"],
    description: "Ош базар / Дордой: яблоки, арбуз, сухофрукты. Цена с ценника, без предоплаты.",
    city: "bishkek",
    address: "Дордой, ряд 14",
    lat: 42.9162,
    lng: 74.6164,
    contacts: { phone: "555000101", whatsapp: true },
    pickup: true,
    delivery: false,
    coverUrl: "/sections/shops.jpg",
    status: "active",
    aiConfirmed: true,
    createdAt: now,
    updatedAt: now,
    products: [
      product({
        id: "seed-apple-kg",
        shopId: "seed-dordoi-fruit",
        title: "Яблоки сезонные",
        description: "1 кг, с прилавка",
        category: "food",
        kind: "food-produce",
        price: 85,
        unit: "kg",
        stock: "in",
        quantity: 40,
        photo: "/sections/shops.jpg",
      }),
      product({
        id: "seed-kuraga",
        shopId: "seed-dordoi-fruit",
        title: "Курага",
        description: "Сухофрукты, 1 кг",
        category: "food",
        kind: "food-sweets",
        price: 280,
        unit: "kg",
        stock: "in",
        quantity: 12,
        photo: "/sections/shops.jpg",
      }),
    ],
  },
  {
    id: "seed-osh-spices",
    name: "Лавка «Навруз»",
    ownerPhone: "555000202",
    ownerName: "Бекзат",
    category: "food",
    extraCategories: [],
    kinds: ["food-staples"],
    description: "Ош базар: специи, рис, масло. Смотрите товар на месте.",
    city: "osh",
    address: "Ош базар, восточный ряд",
    lat: 40.5283,
    lng: 72.7985,
    contacts: { phone: "555000202", telegram: true },
    pickup: true,
    delivery: false,
    coverUrl: "/sections/shops.jpg",
    status: "active",
    aiConfirmed: true,
    createdAt: now,
    updatedAt: now,
    products: [
      product({
        id: "seed-rice",
        shopId: "seed-osh-spices",
        title: "Рис краснодарский",
        description: "Мешок 5 кг",
        category: "food",
        kind: "food-staples",
        price: 520,
        unit: "pack",
        stock: "in",
        quantity: 18,
        photo: "/sections/shops.jpg",
      }),
    ],
  },
];
