export const JOB_TYPES = ["full", "part", "gig", "remote", "shift", "intern"] as const;
export type JobType = (typeof JOB_TYPES)[number];

export type JobRow = {
  sphere: string;
  sub: string;
  role: string;
};

/** Spheres / subcategories / roles from konshu_vacancies_data. */
export const JOB_SPHERES = ["it", "sales", "construction", "logistics", "hospitality", "beauty", "education", "household", "finance", "production", "security", "admin", "marketing", "agriculture", "legal", "management"] as const;

export const JOB_ROWS: JobRow[] = [
  { sphere: "it", sub: "razrabotka", role: "backend-razrabotchik" },
  { sphere: "it", sub: "razrabotka", role: "frontend-razrabotchik" },
  { sphere: "it", sub: "razrabotka", role: "mobilnyy-razrabotchik" },
  { sphere: "it", sub: "razrabotka", role: "fullstack-razrabotchik" },
  { sphere: "it", sub: "dizayn-i-ux", role: "ui-ux-dizayner" },
  { sphere: "it", sub: "dizayn-i-ux", role: "graficheskiy-dizayner" },
  { sphere: "it", sub: "testirovanie-i-podderzhka", role: "qa-inzhener" },
  { sphere: "it", sub: "testirovanie-i-podderzhka", role: "sistemnyy-administrator" },
  { sphere: "it", sub: "testirovanie-i-podderzhka", role: "it-spetsialist-podderzhki" },
  { sphere: "sales", sub: "roznichnye-prodazhi", role: "prodavets-konsultant" },
  { sphere: "sales", sub: "roznichnye-prodazhi", role: "kassir" },
  { sphere: "sales", sub: "optovye-prodazhi-i-b2b", role: "menedzher-po-prodazham" },
  { sphere: "sales", sub: "optovye-prodazhi-i-b2b", role: "torgovyy-predstavitel" },
  { sphere: "sales", sub: "upravlenie-prodazhami", role: "rukovoditel-otdela-prodazh" },
  { sphere: "construction", sub: "inzhenerno-tehnicheskiy-personal", role: "prorab" },
  { sphere: "construction", sub: "inzhenerno-tehnicheskiy-personal", role: "inzhener-pto" },
  { sphere: "construction", sub: "inzhenerno-tehnicheskiy-personal", role: "smetchik" },
  { sphere: "construction", sub: "rabochie-spetsialnosti", role: "kamenschik" },
  { sphere: "construction", sub: "rabochie-spetsialnosti", role: "svarschik" },
  { sphere: "construction", sub: "rabochie-spetsialnosti", role: "elektrik" },
  { sphere: "construction", sub: "rabochie-spetsialnosti", role: "raznorabochiy" },
  { sphere: "construction", sub: "otdelochnye-raboty", role: "malyar-shtukatur" },
  { sphere: "construction", sub: "otdelochnye-raboty", role: "plitochnik" },
  { sphere: "logistics", sub: "voditeli", role: "voditel-kategorii-b" },
  { sphere: "logistics", sub: "voditeli", role: "voditel-kategorii-c-e" },
  { sphere: "logistics", sub: "voditeli", role: "voditel-ekspeditor" },
  { sphere: "logistics", sub: "kurerskaya-dostavka", role: "kurer-peshiy" },
  { sphere: "logistics", sub: "kurerskaya-dostavka", role: "kurer-na-avto" },
  { sphere: "logistics", sub: "skladskaya-logistika", role: "kladovschik" },
  { sphere: "logistics", sub: "skladskaya-logistika", role: "gruzchik" },
  { sphere: "logistics", sub: "skladskaya-logistika", role: "logist" },
  { sphere: "hospitality", sub: "kuhnya", role: "povar" },
  { sphere: "hospitality", sub: "kuhnya", role: "su-shef" },
  { sphere: "hospitality", sub: "kuhnya", role: "konditer" },
  { sphere: "hospitality", sub: "zal-i-servis", role: "ofitsiant" },
  { sphere: "hospitality", sub: "zal-i-servis", role: "barmen" },
  { sphere: "hospitality", sub: "gostinichnyy-servis", role: "administrator-gostinitsy" },
  { sphere: "hospitality", sub: "gostinichnyy-servis", role: "gornichnaya" },
  { sphere: "beauty", sub: "salonnye-uslugi", role: "parikmaher" },
  { sphere: "beauty", sub: "salonnye-uslugi", role: "master-manikyura" },
  { sphere: "beauty", sub: "salonnye-uslugi", role: "kosmetolog" },
  { sphere: "beauty", sub: "meditsina", role: "vrach" },
  { sphere: "beauty", sub: "meditsina", role: "medsestra-medbrat" },
  { sphere: "beauty", sub: "meditsina", role: "farmatsevt" },
  { sphere: "education", sub: "shkolnoe-i-doshkolnoe", role: "uchitel" },
  { sphere: "education", sub: "shkolnoe-i-doshkolnoe", role: "vospitatel-detskogo-sada" },
  { sphere: "education", sub: "dopolnitelnoe-obrazovanie", role: "repetitor" },
  { sphere: "education", sub: "dopolnitelnoe-obrazovanie", role: "trener-instruktor" },
  { sphere: "household", sub: "uhod-za-domom", role: "domrabotnitsa" },
  { sphere: "household", sub: "uhod-za-domom", role: "nyanya" },
  { sphere: "household", sub: "uhod-za-domom", role: "sadovnik" },
  { sphere: "household", sub: "lichnyy-personal", role: "lichnyy-voditel" },
  { sphere: "finance", sub: "uchet", role: "buhgalter" },
  { sphere: "finance", sub: "uchet", role: "kassir-operatsionist" },
  { sphere: "finance", sub: "finansy-i-kredit", role: "finansovyy-menedzher" },
  { sphere: "finance", sub: "finansy-i-kredit", role: "kreditnyy-spetsialist" },
  { sphere: "production", sub: "rabochie-professii", role: "operator-stanka" },
  { sphere: "production", sub: "rabochie-professii", role: "slesar" },
  { sphere: "production", sub: "rabochie-professii", role: "shveya" },
  { sphere: "production", sub: "itr-proizvodstva", role: "inzhener-tehnolog" },
  { sphere: "production", sub: "itr-proizvodstva", role: "nachalnik-tseha" },
  { sphere: "security", sub: "ohrannaya-deyatelnost", role: "ohrannik" },
  { sphere: "security", sub: "ohrannaya-deyatelnost", role: "sotrudnik-sluzhby-bezopasnosti" },
  { sphere: "admin", sub: "ofis-menedzhment", role: "sekretar" },
  { sphere: "admin", sub: "ofis-menedzhment", role: "ofis-menedzher" },
  { sphere: "admin", sub: "podbor-personala", role: "hr-menedzher" },
  { sphere: "admin", sub: "podbor-personala", role: "rekruter" },
  { sphere: "marketing", sub: "marketing", role: "marketolog" },
  { sphere: "marketing", sub: "marketing", role: "smm-spetsialist" },
  { sphere: "marketing", sub: "reklama-i-pr", role: "pr-menedzher" },
  { sphere: "marketing", sub: "reklama-i-pr", role: "targetolog" },
  { sphere: "agriculture", sub: "rastenievodstvo", role: "agronom" },
  { sphere: "agriculture", sub: "rastenievodstvo", role: "traktorist" },
  { sphere: "agriculture", sub: "zhivotnovodstvo", role: "zootehnik" },
  { sphere: "agriculture", sub: "zhivotnovodstvo", role: "veterinar" },
  { sphere: "legal", sub: "yuridicheskie-uslugi", role: "yurist" },
  { sphere: "legal", sub: "yuridicheskie-uslugi", role: "yuriskonsult" },
  { sphere: "management", sub: "rukovodstvo-kompaniey", role: "direktor" },
  { sphere: "management", sub: "rukovodstvo-kompaniey", role: "zamestitel-direktora" },
  { sphere: "management", sub: "rukovodstvo-kompaniey", role: "upravlyayuschiy-filialom" },
];

export const JOB_SPHERE_RU: Record<string, string> = {
  "it": "IT, интернет, телеком",
  "sales": "Продажи",
  "construction": "Строительство и ремонт",
  "logistics": "Транспорт и логистика",
  "hospitality": "Общепит, рестораны, гостиницы",
  "beauty": "Красота и здоровье",
  "education": "Образование",
  "household": "Домашний персонал",
  "finance": "Бухгалтерия и финансы",
  "production": "Производство",
  "security": "Охрана и безопасность",
  "admin": "Административная работа, HR",
  "marketing": "Маркетинг, реклама, PR",
  "agriculture": "Сельское хозяйство",
  "legal": "Юриспруденция",
  "management": "Топ-менеджмент и управление",
};
export const JOB_SPHERE_KY: Record<string, string> = {
  "it": "IT, интернет, телеком",
  "sales": "Сатуу",
  "construction": "Курулуш жана оңдоо",
  "logistics": "Транспорт жана логистика",
  "hospitality": "Ашкана, ресторан, мейманкана",
  "beauty": "Сулуулук жана ден соолук",
  "education": "Билим берүү",
  "household": "Үй персоналы",
  "finance": "Бухгалтерия жана финансы",
  "production": "Өндүрүш",
  "security": "Коопсуздук",
  "admin": "Администрация, HR",
  "marketing": "Маркетинг, жарнама, PR",
  "agriculture": "Айыл чарба",
  "legal": "Юриспруденция",
  "management": "Жетекчилик",
};
export const JOB_SPHERE_UZ: Record<string, string> = {
  "it": "IT, internet, telekom",
  "sales": "Sotuv",
  "construction": "Qurilish va taʼmir",
  "logistics": "Transport va logistika",
  "hospitality": "Oshxona, restoran, mehmonxona",
  "beauty": "Goʻzallik va salomatlik",
  "education": "Taʼlim",
  "household": "Uy xodimlari",
  "finance": "Buxgalteriya va moliya",
  "production": "Ishlab chiqarish",
  "security": "Xavfsizlik",
  "admin": "Maʼmuriyat, HR",
  "marketing": "Marketing, reklama, PR",
  "agriculture": "Qishloq xoʻjaligi",
  "legal": "Yurisprudensiya",
  "management": "Rahbariyat",
};
export const JOB_SUB_RU: Record<string, string> = {
  "razrabotka": "Разработка",
  "dizayn-i-ux": "Дизайн и UX",
  "testirovanie-i-podderzhka": "Тестирование и поддержка",
  "roznichnye-prodazhi": "Розничные продажи",
  "optovye-prodazhi-i-b2b": "Оптовые продажи и B2B",
  "upravlenie-prodazhami": "Управление продажами",
  "inzhenerno-tehnicheskiy-personal": "Инженерно-технический персонал",
  "rabochie-spetsialnosti": "Рабочие специальности",
  "otdelochnye-raboty": "Отделочные работы",
  "voditeli": "Водители",
  "kurerskaya-dostavka": "Курьерская доставка",
  "skladskaya-logistika": "Складская логистика",
  "kuhnya": "Кухня",
  "zal-i-servis": "Зал и сервис",
  "gostinichnyy-servis": "Гостиничный сервис",
  "salonnye-uslugi": "Салонные услуги",
  "meditsina": "Медицина",
  "shkolnoe-i-doshkolnoe": "Школьное и дошкольное",
  "dopolnitelnoe-obrazovanie": "Дополнительное образование",
  "uhod-za-domom": "Уход за домом",
  "lichnyy-personal": "Личный персонал",
  "uchet": "Учёт",
  "finansy-i-kredit": "Финансы и кредит",
  "rabochie-professii": "Рабочие профессии",
  "itr-proizvodstva": "ИТР производства",
  "ohrannaya-deyatelnost": "Охранная деятельность",
  "ofis-menedzhment": "Офис-менеджмент",
  "podbor-personala": "Подбор персонала",
  "marketing": "Маркетинг",
  "reklama-i-pr": "Реклама и PR",
  "rastenievodstvo": "Растениеводство",
  "zhivotnovodstvo": "Животноводство",
  "yuridicheskie-uslugi": "Юридические услуги",
  "rukovodstvo-kompaniey": "Руководство компанией",
};
export const JOB_ROLE_RU: Record<string, string> = {
  "backend-razrabotchik": "Backend-разработчик",
  "frontend-razrabotchik": "Frontend-разработчик",
  "mobilnyy-razrabotchik": "Мобильный разработчик",
  "fullstack-razrabotchik": "Fullstack-разработчик",
  "ui-ux-dizayner": "UI/UX-дизайнер",
  "graficheskiy-dizayner": "Графический дизайнер",
  "qa-inzhener": "QA-инженер",
  "sistemnyy-administrator": "Системный администратор",
  "it-spetsialist-podderzhki": "IT-специалист поддержки",
  "prodavets-konsultant": "Продавец-консультант",
  "kassir": "Кассир",
  "menedzher-po-prodazham": "Менеджер по продажам",
  "torgovyy-predstavitel": "Торговый представитель",
  "rukovoditel-otdela-prodazh": "Руководитель отдела продаж",
  "prorab": "Прораб",
  "inzhener-pto": "Инженер ПТО",
  "smetchik": "Сметчик",
  "kamenschik": "Каменщик",
  "svarschik": "Сварщик",
  "elektrik": "Электрик",
  "raznorabochiy": "Разнорабочий",
  "malyar-shtukatur": "Маляр-штукатур",
  "plitochnik": "Плиточник",
  "voditel-kategorii-b": "Водитель категории B",
  "voditel-kategorii-c-e": "Водитель категории C/E",
  "voditel-ekspeditor": "Водитель-экспедитор",
  "kurer-peshiy": "Курьер пеший",
  "kurer-na-avto": "Курьер на авто",
  "kladovschik": "Кладовщик",
  "gruzchik": "Грузчик",
  "logist": "Логист",
  "povar": "Повар",
  "su-shef": "Су-шеф",
  "konditer": "Кондитер",
  "ofitsiant": "Официант",
  "barmen": "Бармен",
  "administrator-gostinitsy": "Администратор гостиницы",
  "gornichnaya": "Горничная",
  "parikmaher": "Парикмахер",
  "master-manikyura": "Мастер маникюра",
  "kosmetolog": "Косметолог",
  "vrach": "Врач",
  "medsestra-medbrat": "Медсестра / медбрат",
  "farmatsevt": "Фармацевт",
  "uchitel": "Учитель",
  "vospitatel-detskogo-sada": "Воспитатель детского сада",
  "repetitor": "Репетитор",
  "trener-instruktor": "Тренер / инструктор",
  "domrabotnitsa": "Домработница",
  "nyanya": "Няня",
  "sadovnik": "Садовник",
  "lichnyy-voditel": "Личный водитель",
  "buhgalter": "Бухгалтер",
  "kassir-operatsionist": "Кассир-операционист",
  "finansovyy-menedzher": "Финансовый менеджер",
  "kreditnyy-spetsialist": "Кредитный специалист",
  "operator-stanka": "Оператор станка",
  "slesar": "Слесарь",
  "shveya": "Швея",
  "inzhener-tehnolog": "Инженер-технолог",
  "nachalnik-tseha": "Начальник цеха",
  "ohrannik": "Охранник",
  "sotrudnik-sluzhby-bezopasnosti": "Сотрудник службы безопасности",
  "sekretar": "Секретарь",
  "ofis-menedzher": "Офис-менеджер",
  "hr-menedzher": "HR-менеджер",
  "rekruter": "Рекрутер",
  "marketolog": "Маркетолог",
  "smm-spetsialist": "SMM-специалист",
  "pr-menedzher": "PR-менеджер",
  "targetolog": "Таргетолог",
  "agronom": "Агроном",
  "traktorist": "Тракторист",
  "zootehnik": "Зоотехник",
  "veterinar": "Ветеринар",
  "yurist": "Юрист",
  "yuriskonsult": "Юрисконсульт",
  "direktor": "Директор",
  "zamestitel-direktora": "Заместитель директора",
  "upravlyayuschiy-filialom": "Управляющий филиалом",
};
export const JOB_TYPE_RU: Record<string, string> = {
  full: "Полная занятость",
  part: "Частичная занятость",
  gig: "Подработка",
  remote: "Удалённая работа",
  shift: "Вахта",
  intern: "Стажировка",
};
export const JOB_TYPE_KY: Record<string, string> = {
  full: "Толук жумуш күнү",
  part: "Жарым ставка",
  gig: "Кошумча иш",
  remote: "Алыстан иштөө",
  shift: "Вахта",
  intern: "Стажировка",
};
export const JOB_TYPE_UZ: Record<string, string> = {
  full: "Toʻliq bandlik",
  part: "Qisman bandlik",
  gig: "Qoʻshimcha ish",
  remote: "Masofaviy ish",
  shift: "Vaxta",
  intern: "Stajirovka",
};


function unique(ids: string[]) {
  return [...new Set(ids)];
}

export function isJobType(id: string | null | undefined): id is JobType {
  return JOB_TYPES.includes(id as JobType);
}

export function isJobSphere(id: string | null | undefined): boolean {
  return Boolean(id && (JOB_SPHERES as readonly string[]).includes(id));
}

export function jobSubsOf(sphere?: string | null): string[] {
  return unique(JOB_ROWS.filter((row) => !sphere || sphere === "any" || row.sphere === sphere).map((row) => row.sub));
}

export function jobRolesOf(sphere?: string | null, sub?: string | null): string[] {
  return unique(
    JOB_ROWS.filter((row) => {
      if (sphere && sphere !== "any" && row.sphere !== sphere) return false;
      if (sub && sub !== "any" && row.sub !== sub) return false;
      return true;
    }).map((row) => row.role),
  );
}
